### ISSUE TITLE
Добавить установку реквизитов в режиме ОбменДанными.Загрузка в групповой обработке

### ISSUE THREAD

**Issue by borisovcpr** [cpr1c/tools_ui_1c#103]
![image](https://user-images.githubusercontent.com/36307480/74106523-c9adf100-4b78-11ea-917e-796d579c6d42.png)

**Comment by LevkinSergey** [comment]
реализовано в версии 1.4.3 во всех инструментах в которых происходит запись обектов
![image](https://user-images.githubusercontent.com/36307272/74107342-d71aa980-4b7f-11ea-960a-e704847d1e19.png)
