### ISSUE TITLE
Ошибка при перетаскивании поля в поля группировки в консоли запросов

### ISSUE THREAD

**Issue by borisovcpr** [cpr1c/tools_ui_1c#116]
Версия 1.4.2
Исходный запрос:
```
ВЫБРАТЬ
	ХозрасчетныйОборотыДтКт.Регистратор КАК Регистратор,
	СУММА(ХозрасчетныйОборотыДтКт.СуммаОборот) КАК СуммаОборот
ПОМЕСТИТЬ ВТ_БУ
ИЗ
	РегистрБухгалтерии.Хозрасчетный.ОборотыДтКт(&Нач, &Кон, Регистратор, СчетДт = &Счет51, , СчетКт = &Счет76, , ) КАК ХозрасчетныйОборотыДтКт

СГРУППИРОВАТЬ ПО
	ХозрасчетныйОборотыДтКт.Регистратор
```

Добавляю в конструкторе организацию и пытаюсь перетащить ее в поля группировки. Ошибка:
![image](https://user-images.githubusercontent.com/36307480/75347018-ece2db00-58b0-11ea-8b60-c7f8d279b7d5.png)

**Comment by LevkinSergey** [comment]
ЭТо платформенная штука. 
К сожалению на нее повлиять не могу. Только если делать свой конструктор запросов, но это неблагодарное дело
