### ISSUE TITLE
Консоль запросов

### ISSUE THREAD

**Issue by SMichael2020** [cpr1c/tools_ui_1c#131]
Нет возможности передать в параметры запроса группу справочника для проверки на вхождение.
Желательно добавить в параметры запроса виды сравнения.

**Comment by LevkinSergey** [comment]
> Нет возможности передать в параметры запроса группу справочника для проверки на вхождение.

Скиньте скрин, пожалуйста. У себя пробую и у меня не получается повторить ошибку


> Желательно добавить в параметры запроса виды сравнения.

Как понимаю, нужен механиз как в ИР, который работает следующим образом. Делаем запрос, у нас становится доступным поле отбора/сортировки/группировки, в нем делаем настройки и результат формируется в соответствии с установленными фильтрами?
![image](https://user-images.githubusercontent.com/36307272/77478662-6548a780-6e2f-11ea-8421-a894e20bd060.png)

**Comment by borisovcpr** [comment]
Столкнулся с той же проблемой. Вот скрин:
![image](https://user-images.githubusercontent.com/36307480/79121561-3ecabc00-7d9e-11ea-90d2-954466753602.png)
1. По кнопке "Заполнить" не определяет тип параметра
2. Не дает выбрать группу

Вот фрагмент запроса:
```
ВЫБРАТЬ
		ПоступлениеНаРасчетныйСчет.Контрагент КАК Контрагент,
		ПоступлениеНаРасчетныйСчет.ДоговорКонтрагента КАК ДоговорКонтрагента,
		ПоступлениеНаРасчетныйСчет.СуммаДокумента КАК СуммаОплаты
	ИЗ
		Документ.ПоступлениеНаРасчетныйСчет КАК ПоступлениеНаРасчетныйСчет
	ГДЕ
		ПоступлениеНаРасчетныйСчет.Контрагент В ИЕРАРХИИ(&Производители)
```

**Comment by borisovcpr** [comment]
Вариант доработки в форме УИ_КонсольЗапросов  - Форма
```
&НаКлиенте
Процедура вУстановитьОграничениеТипаНаПараметрЗапроса(Знач Значение)
	ЭФ = Элементы._ПараметрыЗапросаЗначение;
	Если Значение = Неопределено Тогда
		ЭФ.ОграничениеТипа = Новый ОписаниеТипов;
	Иначе
		Массив = Новый Массив;
		Массив.Добавить(ТипЗнч(Значение));
		ЭФ.ОграничениеТипа = Новый ОписаниеТипов(Массив);
		//+++
		Если ЭтоСправочник(ТипЗнч(Значение)) Тогда
			ЭФ.ВыборГруппИЭлементов = ГруппыИЭлементы.ГруппыИЭлементы;
		Иначе
			ЭФ.ВыборГруппИЭлементов = ГруппыИЭлементы.Авто;
		КонецЕсли;
		//---
	КонецЕсли;
КонецПроцедуры
//+++
&НаСервереБезКонтекста
Функция ЭтоСправочник(ТипЗначения)
	Возврат Справочники.ТипВсеСсылки().СодержитТип(ТипЗначения);	
КонецФункции
//---

```

**Comment by LevkinSergey** [comment]
В релизе 1.4.6 встроена новая консоль запросов. В ней данная ошибка не повторяется
