### ISSUE TITLE
Ошибка в консоли запросов

### ISSUE THREAD

**Issue by dzottula** [cpr1c/tools_ui_1c#133]
При заполнении параметров из запроса, если оставить параметр (ссылка на справочник) пустым, то не подставляется пустая ссылка этого справочника. Приходится руками вписывать в запрос значение параметра " Значение(Справочник.ИмяСправочника.ПустаяСсылка) "

**Comment by LevkinSergey** [comment]
ИСправлено в версии 1.4.6
