### ISSUE TITLE
Ошибка при открытии обработки УИ_ЗагрузкаДанныхИзТабличногоДокумента

### ISSUE THREAD

**Issue by emayskiy** [cpr1c/tools_ui_1c#158]
Если объект метаданных, который загружали в этой базе ранее, был удален или переименован, то при открытии обработки выходит ошибка "Поле объекта не обнаружено (ИмяОбъектаМетаданных)". 

Ошибка в функции Форма.ПолучитьМетаданныеИсточника() строка №481:
Возврат Метаданные.Справочники[Объект.ТипОбъектаСправочника];

**Comment by LevkinSergey** [comment]
слил изменения. Спасибо
