### ISSUE TITLE
Редактор HTML

### ISSUE THREAD

**Issue by dzottula** [cpr1c/tools_ui_1c#161]
Представляет собой экран разбитый на 4 части, в левой-верхней поле для HTML, право-верх CSS, лево-низ JS, а право-низ - поле результата. Кнопка "запуск" собирает из 3 редактируемых полей - поле результата. Отдельно, галками добавить возможность подключения стандартных библиотек (bootstrap, jquery, AwesomFont и тд, плюс возможность добавлять свои библиотеки URLом). Желательна подсветка операторов, автозаполнение, ну и возможность сворачивать блоки кода.

**Comment by LevkinSergey** [comment]
Библиотека для редактора кода
https://codemirror.net

Пример из мира web https://jsfiddle.net/

**Comment by LevkinSergey** [comment]
https://ace.c9.io/

**Comment by LevkinSergey** [comment]
https://microsoft.github.io/monaco-editor/index.html

**Comment by LevkinSergey** [comment]
Монако огонь, но не работает в 1С. ять

**Comment by LevkinSergey** [comment]
Сделал в версии 1.4.6
