### ISSUE TITLE
Добавить базовую авторизацию и авторизацию NTML в консоль HTTP

### ISSUE THREAD

**Issue by LevkinSergey** [cpr1c/tools_ui_1c#169]

**Comment by free-archer** [comment]
@LevkinSergey не знаешь сервисов, где можно авторизацию тестить? Есть разные fake api, но без авторизации.

**Comment by LevkinSergey** [comment]
> @LevkinSergey не знаешь сервисов, где можно авторизацию тестить? Есть разные fake api, но без авторизации.

Ну базовую можно к любой опубликованной 1С. 
Нашел вот такое https://authenticationtest.com/
