### ISSUE TITLE
сделать свертку панели истории в консоли HTTP

### ISSUE THREAD

**Issue by LevkinSergey** [cpr1c/tools_ui_1c#173]

**Comment by free-archer** [comment]
Есть предложение по изменению интерфейса
https://github.com/cpr1c/tools_ui_1c/issues/532

**Comment by LevkinSergey** [comment]
Я думал переработать интерфейс, чтобы он был похож на insomnia или postman.
Можно все по вкладкам разложить. 
В любом случае с #532 будет лучше чем сейчас.

**Comment by LevkinSergey** [comment]
@free-archer вот как выглядит инсомния 
![image](https://github.com/cpr1c/tools_ui_1c/assets/36307272/1ab62272-49bb-4dbe-acee-75c639ff9f2a)

**Comment by free-archer** [comment]
@LevkinSergey посмотрел insomnia. Неплохо, может даже удобнее чем postman. Не так интерфейс перегружен.
Но по сути они схожи, только у postman вертикальная группировка, а у insomnia горизонтальная .

Но не в одном из них нет Истории, а в Консоли HTTP история сделана центральным элементом. Эта задумка мне не очень понятна.
Можно конечно историю разместить вместо дерева проекта слева, оставив одну колонку адреса, но как то те туда не сюда...

Либо прям кардинально менять. Добавлять список проектов, а историю скрывать. Но тут и сохранение настроек придется переделывать полностью.

**Comment by LevkinSergey** [comment]
> @LevkinSergey посмотрел insomnia. Неплохо, может даже удобнее чем postman. Не так интерфейс перегружен. Но по сути они схожи, только у postman вертикальная группировка, а у insomnia горизонтальная .
> 
> Но не в одном из них нет Истории, а в Консоли HTTP история сделана центральным элементом. Эта задумка мне не очень понятна. Можно конечно историю разместить вместо дерева проекта слева, оставив одну колонку адреса, но как то те туда не сюда...
> 
> Либо прям кардинально менять. Добавлять список проектов, а историю скрывать. Но тут и сохранение настроек придется переделывать полностью.

Не знаю как в постмане, но в инсомнии история точно есть. Она там не общая, а на каждый конкретный запрос идет. 
![image](https://github.com/cpr1c/tools_ui_1c/assets/36307272/b08cd25d-673b-4205-9d0f-aa9b10cd906f)

По поводу истории и ее центральности в консоли - это было не самое удачное решение. 
Сейчас видение, что нужно кардинально менять концепцию. Делать как в консоли запросов дерево запросов, Отдельно закладку с параметрами запроса и результатом запроса(например, как в инсомнии). Отдельная закладка с историей запросов для возможности просмотра запроса и его результата потом
Соответственно в файл сохранять дерево запросов, а историю сохранять в кэш инструментов на сервере. 

Вот примерное расположение. 
![untitled_page](https://github.com/cpr1c/tools_ui_1c/assets/36307272/87f3dd8d-3eff-47e8-9fc4-dffca58db245)

**Comment by free-archer** [comment]
Вот так получается

![image](https://github.com/cpr1c/tools_ui_1c/assets/36464371/ca7271f0-fd1c-4533-b7d3-dd1e89c14d6e)
