### ISSUE TITLE
В новой консоли запросов (1.4.6) не хватает возможности обработать результат запроса, есть только Выборка

### ISSUE THREAD

**Issue by borisovcpr** [cpr1c/tools_ui_1c#190]
Например, мне нужно обработать строки табличной части нескольких документов. Сейчас приходится получать объект при обработке каждой строки, а хотелось бы итоги по ссылке и обработать строки табличной части при обходе детальных записей.

**Comment by JohnyDeath** [comment]
@borisovcpr не совсем понял что именно хотите. Можете пример запроса и кода предоставить?

**Comment by borisovcpr** [comment]
Например, выбираем строки табличной части по определенному условию и собираем по документу

```
ВЫБРАТЬ
	Товары.Ссылка КАК Ссылка,
	Товары.НомерСтроки КАК НомерСтроки
ИЗ
	Документ.ПоступлениеТоваровУслуг.Товары КАК Товары
ГДЕ
	Товары.СтавкаНДС = ЗНАЧЕНИЕ(Перечисление.СтавкиНДС.ПустаяСсылка)
ИТОГИ ПО
	Ссылка
```

Далее хотелось бы через результат запроса обойти выборку по документам, получить объект один раз, а затем обойти необходимые строки. Примерно так:

```
ВыборкаДок = РезультатЗапроса.Выбрать(ОбходРезультатаЗапроса.ПоГруппировкам);

Пока ВыборкаДок.Следующий() Цикл
	
	ДокОбъект = ВыборкаДок.Ссылка.ПолучитьОбъект();
	
	ВыборкаСтроки = ВыборкаДок.Выбрать();
	
	Пока ВыборкаСтроки.Следующий() Цикл
		ДокОбъект.Товары[ВыборкаСтроки.НомерСтроки-1].СтавкаНДС = Перечисления.СтавкиНДС.БезНДС;	
	КонецЦикла;
	
	ДокОбъект.Записать();
	
КонецЦикла;
```

**Comment by borisovcpr** [comment]
Судя по описанию, доступна только Выборка, но не результат запроса:

> Простое выполнение
> 
> Код просто выполняется на сервере, выполнение происходит один раз. В этом режиме на клиенте нет никакой индикации прогресса выполнения. Обход результата запроса необходимо организовать самостоятельно. В коде можно использовать Сообщить, но сообщения можно будет увидеть только после завершения выполнения. Можно рекомендовать такой вариант, если алгоритм выполняется не долго.
> 
> Переменные, доступные в коде:
> 
> Выборка - выборка из результата запроса.
> 
> Параметры - параметры запроса.
> 
> Пример.
> Пока Выборка.Следующий() Цикл
>     Выборка.Ссылка.ПолучитьОбъект().Удалить();
> КонецЦикла;

**Comment by JohnyDeath** [comment]
@borisovcpr у объекта "ВыборкаИзРезультатаЗапроса" есть метод "Владелец", который возвращает РезультатЗапроса, на основании которого выборка была сделана.
Поэтому в вашем случае в коде алгоритма достаточно добавить одну строку в самое начало:

`РезультатЗапроса = Выборка.Владелец();`

**Comment by JohnyDeath** [comment]
@LevkinSergey задачу можно закрывать, как мне кажется

**Comment by LevkinSergey** [comment]
@JohnyDeath я бы эту фичу все-таки реализовал. Сам реже выборкой, чем результатом запроса пользуюсь. Особенно если нужно как-то иерархически обойти результат запроса

**Comment by borisovcpr** [comment]
Никогда этим методом для выборки не пользовался, даже в голову не пришло, что так можно))) 

Может, для варианта "Простое выполнение", где обход выборки нужно делать самостоятельно, расширить доступные параметры? Можно было бы не просто результат, а пакет передавать.

`&НаСервере
Функция ВыполнитьАлгоритм()

	//стРезультатЗапроса = ПолучитьИзВременногоХранилища(АдресРезультатаЗапроса);
	//маРезультатЗапроса = стРезультатЗапроса.Результат;
	//стРезультат = маРезультатЗапроса[Число(РезультатВПакете) - 1];
	//рзВыборка = стРезультат.Результат;
	//выбВыборка = рзВыборка.Выбрать();

	//Попытка
	//	ВыполнитьКод(ТекстАлгоритм.ПолучитьТекст(), выбВыборка, стРезультатЗапроса.Параметры);
	//Исключение
	//	стрСообщениеОбОшибке = ОписаниеОшибки();
	//	Возврат Новый Структура("Успешно, Продолжать, ОписаниеОшибки", Ложь, Ложь, стрСообщениеОбОшибке);
	//КонецПопытки;

	//Возврат Новый Структура("Успешно, Продолжать, ОписаниеОшибки", Истина);

	стРезультатЗапроса = ПолучитьИзВременногоХранилища(АдресРезультатаЗапроса);
	ПакетРезультатов = стРезультатЗапроса.Результат;
	РезультатЗапроса = ПакетРезультатов[Число(РезультатВПакете) - 1].Результат;
	Выборка = РезультатЗапроса.Выбрать();

	Попытка
		ВыполнитьКод(ТекстАлгоритм.ПолучитьТекст(), Выборка, стРезультатЗапроса.Параметры, РезультатЗапроса, ПакетРезультатов);
	Исключение
		стрСообщениеОбОшибке = ОписаниеОшибки();
		Возврат Новый Структура("Успешно, Продолжать, ОписаниеОшибки", Ложь, Ложь, стрСообщениеОбОшибке);
	КонецПопытки;

	Возврат Новый Структура("Успешно, Продолжать, ОписаниеОшибки", Истина);
	
КонецФункции`

**Comment by JohnyDeath** [comment]
@LevkinSergey @borisovcpr 
вы серьезно что ль? проблема ж решается без всяких правок одной строкой кода в начале алгоритма.
так можно запросить и весь контекст в параметры передавать.
я понимаю, когда задача нерешаема без правки Инструментов, но тут явно не этот случай.
