### ISSUE TITLE
Добавить обработку ВременнаяПодменаПароля в состав расширения

### ISSUE THREAD

**Issue by mrChOP93** [cpr1c/tools_ui_1c#192]
Обработка позволяет временно изменять пароль пользователя и возвращать его обратно
[ВременнаяПодменаПароля(base).zip](https://github.com/cpr1c/tools_ui_1c/files/5049275/base.zip)

**Comment by LevkinSergey** [comment]
Реализовано в навигаторе по конфигурации в версии 1.4.8
