### ISSUE TITLE
Консоль запросов. Ошибка преобразования результата запроса в параметр типа список значений или массив

### ISSUE THREAD

**Issue by JohnyDeath** [cpr1c/tools_ui_1c#204]
Версия УИ - 1.46
**Опишите ошибку**
В новой консоли запросов есть прекрасная функция преобразования результата запроса в параметр для его последующего использования. При нажатии на соответствующую кнопку предлагается выбрать тип контейнера:
* Таблица значений 
* Список значений 
* Массив

При выборе контейнера типа Список значений или массив вываливается ошибка

> Несоответствие типов (параметр номер '1')
> {УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.Форма.Форма(1379)}:			НовыйСписок.ЗагрузитьЗначения(КонтейнерМассив);
> {УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.Форма.Форма(2557)}:			ПараметрыЗапроса_УстановитьТип(идСтрокаПараметра, РезультатЗакрытия.ТипКонтейнера, ОписаниеКонтейнера);
> {УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.РедактированиеТипа.Форма(401)}:	Закрыть(ВозвращаемоеЗначение);
> 
> по причине:
> Несоответствие типов (параметр номер '1')

С типом "Таблица значений" ошибок не возникает.

Пример на скрине:
![image](https://user-images.githubusercontent.com/5936030/92924857-a454ce80-f44a-11ea-9cf2-dcd739c1a745.png)
![image](https://user-images.githubusercontent.com/5936030/92924866-a7e85580-f44a-11ea-93e7-e0a1b33dfbca.png)

Текст запроса 
`Выбрать Первые 10
	Контрагенты.Ссылка как Контрагент
Из Справочник.Контрагенты как Контрагенты`

**Окружение**
 - Версия платформы: 8.3.17.1386
 - Режим базы данных(файловая/серверная/веб): серверная
 - Конфигурация: Бух КОРП 3.0
 - Версия конфигурации:
 - ОС: Windows 10

**Comment by LevkinSergey** [comment]
реализовано в тестовой версии
