### ISSUE TITLE
Консоль запросов. Ошибка преобразования результата в табличный документ

### ISSUE THREAD

**Issue by JohnyDeath** [cpr1c/tools_ui_1c#205]
Версия УИ - 1.46
**Опишите ошибку**
Если в консоли запросов нажать на кнопку "В документ" (Вывести результат в табличный документ (F12)), что расположена над таблицей результата, то получаем ошибку

> Поле объекта недоступно для записи (Примечание)
> {УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.ФормаТабличногоДокумента.Форма(158)}:		ОбластьЗаполнения.Примечание = Колонка.ТипЗначения;
> {УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.ФормаТабличногоДокумента.Форма(244)}:	СформироватьДокумент();
> {УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.Форма.Форма(3834)}:	ОткрытьФорму("Обработка.УИ_КонсольЗапросов.Форма.ФормаТабличногоДокумента", ПараметрыОткрытия, ЭтаФорма, Ложь);
> 

**Окружение**
 - Версия платформы: 8.3.17.1386
 - Режим базы данных(файловая/серверная/веб): серверная
 - Конфигурация: Бух КОРП 3.0
 - Версия конфигурации:
 - ОС: Windows 10

**Comment by LevkinSergey** [comment]
Это дубль #207. ЕЕ закрываю. Отписался в связанной задаче
