### ISSUE TITLE
Консоль запросов. Кнопка "В документ"

### ISSUE THREAD

**Issue by JohnyDeath** [cpr1c/tools_ui_1c#207]
Версия УИ - 1.46

При нажатии на кнопку "В документ" результата запроса вываливается ошибка

> Поле объекта недоступно для записи (Примечание)
> {УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.ФормаТабличногоДокумента.Форма(158)}:		ОбластьЗаполнения.Примечание = Колонка.ТипЗначения;
> {УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.ФормаТабличногоДокумента.Форма(244)}:	СформироватьДокумент();
> {УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.Форма.Форма(3834)}:	ОткрытьФорму("Обработка.УИ_КонсольЗапросов.Форма.ФормаТабличногоДокумента", ПараметрыОткрытия, ЭтаФорма, Ложь);
> 

Помогает комментирование (удаление) строки:
https://github.com/cpr1c/tools_ui_1c/blob/develop/Инструменты/src/DataProcessors/УИ_КонсольЗапросов/Forms/ФормаТабличногоДокумента/Module.bsl#L158

(сделать PR пока не могу, не доходят руки до развертывания и настройки EDT)

**Окружение**

Версия платформы: 8.3.17.1386
Режим базы данных(файловая/серверная/веб): серверная
Конфигурация: Бух КОРП 3.0
Версия конфигурации:
ОС: Windows 10

**Comment by LevkinSergey** [comment]
На выходных посмотрю

**Comment by LevkinSergey** [comment]
Неправильно устанавливались примечания в шапке таблицы. 8.3.12 не реагировала на это, а 8.3.17 начала
Вот ссылка на новую сборку 
https://yadi.sk/d/t8VM41x9YQ16pg
