### ISSUE TITLE
Ошибка при удалении (del) элемента из списка в обработке "Групповая обработка справочников и документов"

### ISSUE THREAD

**Issue by MaxKorr** [cpr1c/tools_ui_1c#212]
**Опишите ошибку**
В обработке на закладке "Выбор объектов", добавляем справочник (любой), далее пытаемся его удалить из списка (del), появляется такая ошибка:
Недопустимое значение параметра (параметр номер '1')
{УниверсальныеИнструменты Обработка.УИ_ГрупповаяОбработкаСправочниковИДокументов.Форма.ПодборИОбработка.Форма(903)}:	ТабличноеПолеВидыОбъектов.Удалить(ТекСтрока);
{УниверсальныеИнструменты Обработка.УИ_ГрупповаяОбработкаСправочниковИДокументов.Форма.ПодборИОбработка.Форма(1657)}:	ВыполнитьОбработкуОповещения(ОповщениеОЗавершении, Результат);
{УниверсальныеИнструменты Обработка.УИ_ГрупповаяОбработкаСправочниковИДокументов.Форма.ПодборИОбработка.Форма(1646)}:	ПроверкаНеобходимостиОчищатьРезультатыЗавершение(Истина, ДополнительныеПараметрыОповщения);
{УниверсальныеИнструменты Обработка.УИ_ГрупповаяОбработкаСправочниковИДокументов.Форма.ПодборИОбработка.Форма(892)}:	ПроверкаНеобходимостиОчищатьРезультаты(Новый ОписаниеОповещения("ТабличноеПолеВидыОбъектовПередУдалениемЗавершение",

по причине:
Недопустимое значение параметра (параметр номер '1')

**Воспроизведение ошибки**
1. Запустить обработку Групповая обработка справочников и документов [УИ]
2. На закладке "Выбор объектов" (тип объекта: справочники) выбрать справочник, и попытаться его удалить через клавишу DEL или через контекстное меню. 
3. Увидеть ошибку

**Ожидаемое поведение**
удалить строку с элементом из списка 

**Окружение**
 - Версия платформы: 8.3.16.1502
 - Режим базы данных(файловая/серверная/веб): серверная
 - Конфигурация: 1С:Комплексная автоматизация 2
 - Версия конфигурации: (2.4.12.91)
 - ОС: Windows Server 2019 Standart
 - Версия: 1.4.6
 

**Дополнительная информация**

**Comment by LevkinSergey** [comment]
Исправлено в тестовой версии
