### ISSUE TITLE
Консоль отчетов СКД: При формировании отчета с таблицей возникает ошибка Не поддерживается вывод таблиц и диаграмм в универсальную коллекцию значений

### ISSUE THREAD

**Issue by TonyGuba** [cpr1c/tools_ui_1c#224]
**Опишите ошибку**
При формировании отчета с таблицей возникает ошибка Не поддерживается вывод таблиц и диаграмм в универсальную коллекцию значений и очищается дерево отчетов

**Воспроизведение ошибки**
1. Добавить таблицу в структуре отчета
2. Нажать сформироват
3. Увидеть ошибку

**Ожидаемое поведение**
Если открыта страница Табличный документ, не формировать вывод в коллекцию

**Окружение**
 - Версия платформы: 8.3.17.1549
 - Режим базы данных серверная
- Конфигурация: УТ 11
 - Версия конфигурации: 11.4.11.88
 - ОС: Win10
 - Версия: 1.4.6

**Comment by LevkinSergey** [comment]
Исправлено
