### ISSUE TITLE
Файловый менеджер не работает с сетевыми путями

### ISSUE THREAD

**Issue by puretruth** [cpr1c/tools_ui_1c#226]
**Опишите ошибку**
При переходе по сетевому пути, обработка заменяет двойной слеш (\\) на одинарный (\). В результате невозможно работать с файлами из папки

**Воспроизведение ошибки**
1. Запустить обработку
2. Перейти по сетевому пути
3. Скопировать файл в локальную папку

**Ожидаемое поведение**
Сетевой путь должен обрабатываться корректно, и в результате должна быть возможность работать с файлами в сетевой папке.

**Окружение**
 - Версия платформы: 8.3.15
 - Режим базы данных(файловая/серверная/веб): серверная
 - Конфигурация: УТ 11.4
 - Версия конфигурации: 11/4
 - ОС: Windows
 - Версия: Server 2016
 

**Дополнительная информация**

**Comment by LevkinSergey** [comment]
Исправлено в ветке develop
