### ISSUE TITLE
Возможность копировать табличную часть документа через буфер обмена

### ISSUE THREAD

**Issue by dzottula** [cpr1c/tools_ui_1c#230]
# Описание задачи

**Опишите вашу Цель, которую вы сможете достичь с помощью новой функциональности**
Какую задачу вы смогли бы решить, если бы была предлагаемая Вами функциональность?
_Переносить данные табличной части между документами/базами без использования дополнительных средств._

**Опишите решение**
Четкое и понятное описание того, что Вы хотите видеть в проекте и как именно?
_через xml или json_

**Дополнительная информация**
Любая дополнтельная информация

**Comment by LevkinSergey** [comment]
будет реализовано  в #232
