### ISSUE TITLE
Редактор HTML [УИ] - ошибка сохранения файла

### ISSUE THREAD

**Issue by Mopo3ru** [cpr1c/tools_ui_1c#231]
**Опишите ошибку**
Редактор HTML [УИ] - ошибка сохранения файла.

**Воспроизведение ошибки**
1. Сохранить файл как - указать имя
2. Сохранить файл (без указания имени, по старому пути)

**Дополнительная информация**
Для исправления ошибки:
1. УИ_ОбщегоНазначенияКлиент
2. Процедура СохранитьДанныеКонсолиВФайлПослеПолученияФайлов(ПолученныеФайлы, ДополнительныеПараметры) Экспорт
3. ЗАМЕНИТЬ:
ИмяФайла = ПолученныеФайлы[0].Имя;
НА:
ИмяФайла = ПолученныеФайлы[0].ПолноеИмя; //нужно именно так, иначе в силу специфики реализации инструмента при попытке записи БЕЗ интерактивного указания файла будет ошибка, т.к. в качестве пути сохранения передается не полный путь файла, а просто его имя

Возможно, также дополнительно понадобится сделать (у себя локально исправил, но не проверял, будет ли работать без этого исправления):
1. УИ_ОбщегоНазначенияВызовСервера
2. ПодготовленныеДанныеКонсолиДляЗаписиВФайл()
3. Закрытие объектов ЗаписьДанных и Поток:
	Поток = Новый ПотокВПамяти;
	
	ЗаписьТекста = Новый ЗаписьДанных(Поток);
	ЗаписьТекста.ЗаписатьСтроку(НовыеДанныеСохранения);
	ЗаписьТекста.Закрыть();

	ДвоичныеДанныеФайла = Поток.ЗакрытьИПолучитьДвоичныеДанные();
	
	Поток.Закрыть();

**Comment by LevkinSergey** [comment]
Исправил в новой версии. Проблемы из-за изменения работы с файлоами в платформе 8.3.13
