### ISSUE TITLE
Файловый менеджер не работает копирование с сервера на клиент

### ISSUE THREAD

**Issue by Nicodimych** [cpr1c/tools_ui_1c#233]
Как то понадобилась такая функция , а она оказывается не работает . Т.е. она работает когда кдиент и сервер одна и таже машина , а если разные - то нет.
Процедура СкопироватьНаКлиент(Команда) выполняется целиком на клиенте , поэтому не работает . 
Поменял строку 	СтрокаСтруктура.Вставить("АдресВХранилище", ПоместитьВоВременноеХранилище ...  на 
СтрокаСтруктура.Вставить("АдресВХранилище", ФункцияПоместитьВоВременноеХранилище(СтрокаСтруктура.ПолноеИмя, УникальныйИдентификатор));
и написал функцию 
&НаСервере
Функция  ФункцияПоместитьВоВременноеХранилище(ПолноеИмя, УникальныйИдентификатор)	
	Возврат	ПоместитьВоВременноеХранилище(
	Новый ДвоичныеДанные(ПолноеИмя), УникальныйИдентификатор);	
КонецФункции

После этого заработало.
Там еще первые буквы в названии скопированных файлов пропададают. Но мне надо было буквально пару файлов скопировать , потому дальше я не смотрел )

**Comment by LevkinSergey** [comment]
Исправил в тестовой версии
