### ISSUE TITLE
УИ_КонсольОтчетов - включить возможность использования внешних функций

### ISSUE THREAD

**Issue by worksable** [cpr1c/tools_ui_1c#255]
# Описание задачи
В текущей реализации далеко не со всеми схемами СКД можно работать, т.к. часть из них используют внешние функции.
Приходится править расширение вручную. Это не долго, не сложно, но делает расширение менее универсальным.

**Опишите решение**
В модуле формы "Форма" отчета "УИ_КонсольОтчетов" надо сделать:

//процедура ВывестиМакетКомпоновкиДанныхВТабличныйДокумент, 994 строка кода.
//было
//ПроцессорКомпоновкиДанных.Инициализировать(МакетКомпоновкиДанных, СтруктураВнешнихНаборовДанных(), ДанныеРасшифровкиОбъект, Ложь);
//стало
ПроцессорКомпоновкиДанных.Инициализировать(МакетКомпоновкиДанных, СтруктураВнешнихНаборовДанных(), ДанныеРасшифровкиОбъект, Истина);

**Comment by LevkinSergey** [comment]
Исправлено. Спасибо
