### ISSUE TITLE
Не можем удалить 

### ISSUE THREAD

**Issue by Ashas55** [cpr1c/tools_ui_1c#261]
**Опишите ошибку**
Установил обработку через расширения все нормально работало, но затем коллега, зачем то решил установить ее через конфигуратор, не удалил обработку из расширения и теперь у нас "две обработки" не получается удалить до конца. Делали возврат конфигурации из резервной копии, но та обратка которая установлена через расширения не удаляется. Из-за ошибки "найдены дублирующие записи в менеджере имен базы данных.

**Воспроизведение ошибки**
1. Запустить обработку ...
2. Сделать настройки/Нажать кнопку ...
3. Увидеть ошибку

**Ожидаемое поведение**
Опишите, как должна вести себя система в указаных условиях. 

**Окружение**
 - Версия платформы: 8.3 (8.3.16.1224)
 - Режим базы данных(серверная):
 - Конфигурация: УправлениеТорговлей
 - Версия конфигурации: 11.4.13.85
 - ОС: Windows
 - Версия: х64 
 

**Дополнительная информация**
![2021-02-08_09-19-51](https://user-images.githubusercontent.com/78720053/107186950-3e1ea880-69f6-11eb-9aab-25bbeb1f58f3.png)

**Comment by LevkinSergey** [comment]
Добрый день! 
Можете попробовать из конфигуратора удаление сделать? Или скрин расширений из конфигуратора?
