### ISSUE TITLE
В консоли запросов команда "Вставка предопределенного" не учитывает объекты расширений

### ISSUE THREAD

**Issue by mrkingmidas** [cpr1c/tools_ui_1c#279]
В консоли запросов команда "Вставка предопределенного" (Alt+P) не учитывает объекты расширений, но не полностью: 
- Сам объект виден
- Значения видны
- Выбрать нельзя и подставить конкретное значение!
- Кнопка "ПустаяСсылка" работает

![image](https://user-images.githubusercontent.com/1373772/111624315-94081c80-87fc-11eb-946e-5a89b75c9290.png)

**Comment by tormozit** [comment]
Надо назначить реквизиту формы тип "Произвольный". Тогда заработает. В платформе устранить это досадное ограничение планируют в 8.3.20, т.е. там уже все без доработок и извращений как обещают будет работать.
