### ISSUE TITLE
консоль веб-сервиса

### ISSUE THREAD

**Issue by dzottula** [cpr1c/tools_ui_1c#28]
В одной панельке имя сервиса, ssl или без него,  параметры, заголовки, метод запроса (get, post, delete и ид), лог что отправляется, код возврата, лог что возвращается.

**Comment by LevkinSergey** [comment]
https://github.com/ghostaz/WSReader2.git

**Comment by LevkinSergey** [comment]
Автор дал разрешение. Добавил лицензию в репу.

**Comment by LevkinSergey** [comment]
Включено в релиз 1.4.5
