### ISSUE TITLE
Ошибка открытия формы объекта на Мобильном клиенте

### ISSUE THREAD

**Issue by JohnyDeath** [cpr1c/tools_ui_1c#320]
Версия расширения: 1.4.9 (UI.cfe)
Бухгалтерия предприятия КОРП, редакция 3.0 (3.0.95.24)
1С:Предприятие 8.3 (8.3.18.1334)
Мобильный клиент версии 8.3.18.77

При открытии формы документа в мобильном клиенте вываливается ошибка

> {УниверсальныеИнструменты CommonModule.УИ_ОбщегоНазначенияКлиентСервер.Module(349,10)}: Переменная не определена (Метаданные)

На версии 1.4.8 такой ошибки не возникало

**Comment by JohnyDeath** [comment]
Вот тут https://github.com/cpr1c/tools_ui_1c/blob/develop/src/Инструменты/src/CommonModules/УИ_ОбщегоНазначенияКлиентСервер/Module.bsl#L348
наверное лучше сделать директивы ровно как они описаны в справке, т.е. получится примерно так:

```bsl
Функция КодОсновногоЯзыка() Экспорт
#Если Сервер ИЛИ ТолстыйКлиентУправляемоеПриложение ИЛИ ТолстыйКлиентОбычноеПриложение ИЛИ МобильноеПриложениеСервер ИЛИ МобильныйАвтономныйСервер Тогда
	Возврат Метаданные.ОсновнойЯзык.КодЯзыка;
#Иначе
		Возврат УИ_ОбщегоНазначенияПовтИсп.КодОсновногоЯзыка();
#КонецЕсли
КонецФункции
```

**Comment by LevkinSergey** [comment]
исправил в 1.4.10
