### ISSUE TITLE
Ошибка открытия консоли кода в портативном режиме

### ISSUE THREAD

**Issue by leandr92** [cpr1c/tools_ui_1c#324]
**Опишите ошибку**
При попытке открыть консоль кода возникает ошибка 

"Преобразование значения к типу Булево не может быть выполнено
{ВнешняяОбработка.УИ_РедакторКодаСервер.МодульОбъекта(19)}:			Если Не ПараметрыСеансаВХранилище.ПолеHTMLПостроеноНаWebkit Тогда
{ВнешняяОбработка.УИ_КонсольКода.Форма.Форма.Форма(11)}:	УИ_ГЕНЕРАЦИЯ_ОбщийМодульПоИмени("УИ_РедакторКодаСервер").ФормаПриСозданииНаСервере(ЭтаФорма);
{ВнешняяОбработка.УИ_ПортативныеУниверсальныеИнструменты.Форма.Форма.Форма(123)}:		ОткрытьФорму("ВнешняяОбработка." + Команда.Имя + ".Форма", , ЭтаФорма);
"

**Воспроизведение ошибки**
1. Открыть портативные инструменты
2. Нажать команду "Консоль кода"
3. Увидеть ошибку

**Ожидаемое поведение**
Должна открыться форма консоли

**Окружение**
 - Версия платформы: 8.3.19.1150
 - Режим базы данных(файловая):
 - Конфигурация: Демо БСП
 - Версия конфигурации: 3.0.3.136
 - ОС: Windows x64
 - Версия: 10
 

**Дополнительная информация**

"Параметры сеанса" в хранилище общих настроек оказываются не установлены вовсе.

**Comment by LevkinSergey** [comment]
У себя проверял. Никак не получается смоделировать.

Единственное что на ум приходит - не удается записать или прочитать в хранилище настроек информацию.

Запускал под полноправным пользователем? У него было право СохранениеДанныхПользователя?

**Comment by leandr92** [comment]
> У себя проверял. Никак не получается смоделировать.
> 
> Единственное что на ум приходит - не удается записать или прочитать в хранилище настроек информацию.
> 
> Запускал под полноправным пользователем? У него было право СохранениеДанныхПользователя?

Так точно, запускал под полноправным пользователем. Ты у себя используешь чистую базу для проверки? Возможно ты уже запускал инструменты на ней, и потому в хранилище нужные данные есть.

**Comment by LevkinSergey** [comment]
Пробовал на разных базах. Для чистоты эксперимента сделаю совсем чистую и отпишусь

**Comment by LevkinSergey** [comment]
Удалось повторить на совсем новой базе

**Comment by LevkinSergey** [comment]
Нашел проблему. Оказалось, что чтобы форма стала доступна в результате метода ПолучитьОкна, нужно подождать немного. 

Ниже ссылка на исправленную сборку. Можешь ее у себя попробовать?

[Portable.zip](https://github.com/cpr1c/tools_ui_1c/files/6876448/Portable.zip)

**Comment by leandr92** [comment]
> Нашел проблему. Оказалось, что чтобы форма стала доступна в результате метода ПолучитьОкна, нужно подождать немного. А из-за этого неправильно отрабатывало обращение к параметрам сеанса на клиенте "УИ_ПараметрыПриложения"
> 
> Ниже ссылка на исправленную сборку. Можешь ее у себя попробовать?
> 
> [Portable.zip](https://github.com/cpr1c/tools_ui_1c/files/6876448/Portable.zip)

ок, сегодня попробую

**Comment by leandr92** [comment]
> > Нашел проблему. Оказалось, что чтобы форма стала доступна в результате метода ПолучитьОкна, нужно подождать немного. А из-за этого неправильно отрабатывало обращение к параметрам сеанса на клиенте "УИ_ПараметрыПриложения"
> > Ниже ссылка на исправленную сборку. Можешь ее у себя попробовать?
> > [Portable.zip](https://github.com/cpr1c/tools_ui_1c/files/6876448/Portable.zip)
> 
> ок, сегодня попробую

fixed
