### ISSUE TITLE
В консоли кода Монако НаКлиенте выполняемый код копируется и вставляется в окно выполнения, после чего запускается на выполнение повторно

### ISSUE THREAD

**Issue by it-project-info** [cpr1c/tools_ui_1c#328]
**Опишите ошибку**
В консоли кода Монако НаКлиенте выполняемый код копируется и вставляется в окно выполнения, после чего запускается на выполнение повторно

**Воспроизведение ошибки**
1. Запустить обработку Редактора кода
2. Установить основным редактором Монако
3. Вставить в редактор НаКлиенте код: Если Истина Тогда Сообщить(1); КонецЕсли;
4. Выполнить

**Ожидаемое поведение**
Выполнение алгоритма один раз, отсутствие копирования выполняемого кода с последующей вставкой

**Окружение**
 - Версия платформы: 8.3.18.1334
 - Режим базы данных(файловая/серверная/веб): серверная
 - Конфигурация: Управление торговлей
 - Версия конфигурации: редакция 11 (11.4.13.103)
 - ОС: Windows Server
 - Версия: 2008
 
**Дополнительная информация**
![20210729145522](https://user-images.githubusercontent.com/87799761/127439136-4cd0b954-d090-40b8-9a24-e5bcaf3b9104.png)

**Comment by LevkinSergey** [comment]
Ошибку удалось повторить. Буду разбираться

**Comment by LevkinSergey** [comment]
Исправлено в 1.4.11
