### ISSUE TITLE
Сложный алгоритм кода "клиент - сервер - клиент" и тд 

### ISSUE THREAD

**Issue by FominAV** [cpr1c/tools_ui_1c#334]
# Описание задачи
Сложный алгоритм кода "клиент - сервер - клиент" и тд

**Comment by LevkinSergey** [comment]
При использовании режима исполнения кода с использованием процедур(через обработку) на клиенте можно у процедуры указать директиву компиляции &наСервере и тогда она выполнится на сервере. 
![334](https://github.com/cpr1c/tools_ui_1c/assets/36307272/25844be7-5f5d-4f20-b0fb-90ce77efa043)
