### ISSUE TITLE
Ошибка при чтении html-файлов консоли кода и редактора JSON.

### ISSUE THREAD

**Issue by lo0p3r** [cpr1c/tools_ui_1c#335]
**Опишите ошибку**
При открытии консоли кода или редактора JSON получаю ошибки:
"Couldn't read a file:// file: file:///C:/Users/Sharipov_AN/AppData/Local/Temp/tools_ui_1c/5%C2%A0709/Ace/bsl.html" для редактора Ace, 
"Couldn't read a file:// file: file:///C:/Users/Sharipov_AN/AppData/Local/Temp/tools_ui_1c/5%C2%A0709/Monaco/index.html" для редактора Monaco и
"Couldn't read a file:// file: file:///C:/Users/Sharipov_AN/AppData/Local/Temp/tools_ui_1c/5%C2%A0709/jsoneditor/code.html" для редактора JSON.
Такое поведение получаю и в портативных инструментах и в расширении.

**Воспроизведение ошибки**
1. Запустить обработку "Консоль кода" при установленном редакторе кода Ace или Monaco или запустить Редактор JSON.
2. Увидеть ошибку.

**Ожидаемое поведение**
Запуск редакторов без ошибок.

**Окружение**
 - Версия платформы: 8.3.18.1363
 - Режим базы данных(файловая/серверная/веб): Серверная
 - Конфигурация: Документооборот 8 КОРП, 
 - Версия конфигурации: редакция 2.1 (2.1.28.14)
 - ОС: Windows
 - Версия: 7 Pro x64
 
**Дополнительная информация**
Полагаю, проблема в том, что файлы редакторов создаются в папке с номером сеанса, и если этот номер больше 999, то в строке, полученной путём неявного преобразования из числа, будет неразрывный пробел:
... + "tools_ui_1c" + ПолучитьРазделительПути() + УИ_ОбщегоНазначенияКлиент.НомерСеанса() + ПолучитьРазделительПути() + "jsoneditor";

Проблема решается путём оборачивания номера сеанса в Формат: Формат(УИ_ОбщегоНазначенияКлиент.НомерСеанса(), "ЧГ=").
Места для исправления:
1. Расширение:    ОбщийМодуль.УИ_РедакторКодаКлиент, функция КаталогСохраненияРедактора.
2. Расширение:    Обработка.УИ_РедакторJSON.Форма, функция ПриОткрытииЗавершение.
3. Портативный:  Инструменты\УИ_РедакторJSON.Форма, функция ПриОткрытииЗавершение.
4. Портативный:  ОбщиеМодули\УИ_РедакторКодаКлиент.Форма, функция КаталогСохраненияРедактора.

После внесения таких изменений редактор кода и редактор JSON открываются без ошибок, и в расширении и в портативной версии.

**Comment by lo0p3r** [comment]
Либо можно поправить саму функцию НомерСеанса() из общего модуля УИ_ОбщегоНазначенияКлиент, чтобы она сразу возвращала строку без неразрывного пробела.

**Comment by LevkinSergey** [comment]
Поправил в новой версии. Спасибо
