### ISSUE TITLE
Обновлять встроенные инструменты сторонних авторов

### ISSUE THREAD

**Issue by petypen** [cpr1c/tools_ui_1c#344]
# На примере инструмента "Редактор объектов информационной базы 8.3", который у автора недавно обновлен

Инструмент "Редактор объектов информационной базы 8.3" https://infostart.ru/public/983887/ недавно обновился у автора.  Последняя версия 1.1.0.55 однако, в tools_ui версия старая.

Как можно обновлять встроенные инструменты?
Вы сами это контролируете? Можно (нужно) самостоятельно договариваться с автором и повторно встраивать  инструмент?

**Comment by LevkinSergey** [comment]
Обновления отслеживаю. Есть задачи. Например,  #235. Пока руки никак не дойдут.

С авторами не нужно договариваться. Они уже дали добро. Так что можно брать новую версию встраивать.
 
Если есть желание поучаствовать в обновлении, можно обновить любым удобным способом. Через EDT ([Инструкция](https://github.com/cpr1c/tools_ui_1c/tree/develop/docs/contributing)) или через расширение последней версии и мне его прислать, а я перенесу изменения в репозиторий. Актуальные версии я обычно беру из публикаций авторов или из  открытых репозиториев, если они есть.
