### ISSUE TITLE
Не работает непосредственное удаление в "Редактор реквизитов объекта"

### ISSUE THREAD

**Issue by mrkingmidas** [cpr1c/tools_ui_1c#348]
Не работает непосредственное удаление в "Редактор реквизитов объекта" - при нажатии задается вопрос, "как бы" удаляется, но объект остается.

В коде, видимо, в форме `ФормаОбъекта` обработки `УИ_РедакторРеквизитовОбъекта` в функции `вУдалитьОбъектНаСервере`  в вызове `УИ_ОбщегоНазначения.ЗаписатьОбъектВБазу` нужно передать третий параметр ` НепосредственноеУдаление`

**Comment by VoronyukM** [comment]
Решено в PR к ошибке #416

**Comment by LevkinSergey** [comment]
слил
