### ISSUE TITLE
Консоль запросов. Добавить возможность просматривать свойства текущей строки результата с типами в отдельной таблице

### ISSUE THREAD

**Issue by LevkinSergey** [cpr1c/tools_ui_1c#358]

**Comment by Oleg1085** [comment]
Можешь подробнее написать или пример кинуть, где посмотреть, а то не понятно.

**Comment by LevkinSergey** [comment]
есть такое в ИР 
![image](https://user-images.githubusercontent.com/36307272/164765149-e77d3b46-e66b-46dd-a185-c9bcec20d8cc.png)
