### ISSUE TITLE
В консоли запросов ошибка заполнения параметра с типом Массив или СписокЗначений

### ISSUE THREAD

**Issue by lo0p3r** [cpr1c/tools_ui_1c#374]
**Опишите ошибку**
После заполнения списка значений или массива для параметра и нажатия на "Ок" возникает ошибка "Преобразование значения к типу Число не может быть выполнено":
> Преобразование значения к типу Число не может быть выполнено
> {ВнешняяОбработка.УИ_КонсольЗапросов.МодульОбъекта(1460)}:		Результат = Результат + Разделитель + Строки[сч];
> {ВнешняяОбработка.УИ_КонсольЗапросов.МодульОбъекта(1101)}:			Возврат Лев(_СтрСоединить(Контейнер.СписокЗначений.ВыгрузитьЗначения(), "; "), чРазмерПредставления);
> {ВнешняяОбработка.УИ_КонсольЗапросов.МодульОбъекта(1052)}:		Результат.Представление = Контейнер_ПолучитьПредставление(Результат);
> {ВнешняяОбработка.УИ_КонсольЗапросов.Форма.ПодборВСписок.Форма(56)}:		Возврат РеквизитФормыВЗначение("Объект").Контейнер_СохранитьЗначение(СписокЭлементов.ВыгрузитьЗначения());
> {ВнешняяОбработка.УИ_КонсольЗапросов.Форма.ПодборВСписок.Форма(66)}:	ВозвращаемоеЗначение = Новый Структура("Значение", ПолучитьВозвращаемоеЗначение());
![image](https://user-images.githubusercontent.com/12407761/139190387-415acace-2ee0-4c3e-95a4-2fe84eee7027.png)

**Воспроизведение ошибки**
1. Открыть консоль запросов.
2. Добавить параметр и выбрать **Тип контейнера** массив или список значений.
3. Заполнить список и нажать **Ок**.

**Ожидаемое поведение**
Добавить параметр со списком значений или массивом.

**Окружение**
 - Версия платформы: 8.3.18.1363
 - Режим базы данных(файловая/серверная/веб): серверная
 - Конфигурация: Документооборот 8 КОРП, редакция 2.1
 - Версия конфигурации: 2.1.28.14
 - ОС: Windows
 - Версия: 7 Pro x64
 

**Дополнительная информация**
Версия УИ: 1.4.11

**Comment by Le0x00** [comment]
+1

**Comment by Oleg1085** [comment]
@LevkinSergey а зачем вообще такая реализация? СтрСоединить - Доступен, начиная с версии 8.3.6 (в режиме совместимости с версией 8.3.6 и последующими). Что бы поддерживать версии ниже 8.3.6?

**Comment by LevkinSergey** [comment]
> @LevkinSergey а зачем вообще такая реализация? СтрСоединить - Доступен, начиная с версии 8.3.6 (в режиме совместимости с версией 8.3.6 и последующими). Что бы поддерживать версии ниже 8.3.6?

Да, это на случай когда платформа новая, а режим совместимости старый. Реализовано только в портативном варианте.
Править нужно сборщик. А конкретнее модуль https://github.com/cpr1c/tools_ui_1c/blob/develop/src/builder/Шаблоны/ФункцииСовместимостиСоСтарымиПлатформами.os
Из него функции копируются при сборке

**Comment by LevkinSergey** [comment]
были мысли в реализацию функций вставить проверку на версию совместимости и в большинстве случаев использовать платформенные методы
