### ISSUE TITLE
Возможность показа даты создания ссылки

### ISSUE THREAD

**Issue by LevkinSergey** [cpr1c/tools_ui_1c#381]
&НаСервере
Функция ДатаСозданияСсылки(Ссылка) Экспорт
  ГУИД = Ссылка.УникальныйИдентификатор();
  Строка16 = Сред(ГУИД, 16, 3) + Сред(ГУИД, 10, 4) + Сред(ГУИД, 1, 8);
  Разрядность = СтрДлина(Строка16);
  ЧислоСек = 0;
  Для Позиция = 1 По Разрядность Цикл
    ЧислоСек = ЧислоСек + Найти("123456789abcdef",Сред(Строка16,Позиция,1))*Pow(16,Разрядность - Позиция);
  КонецЦикла;
  ЧислоСек = ЧислоСек / 10000000;
  Возврат Дата(1582, 10, 15, 04, 00, 00) + ЧислоСек;
КонецФункции

**Comment by LevkinSergey** [comment]
Дата(1582, 10, 15, 00, 00, 00) + ЧислоСек + СмещениеСтандартногоВремени() + СмещениеЛетнегоВремени();

**Comment by Oleg1085** [comment]
В консоль запросов где именно дату расположить?

**Comment by LevkinSergey** [comment]
Я думал это делать как макро колонку. 
Т.е. дописываешь в запросе &Ссылка_ДатаСоздания_ и в этой колонке появляется дата создания.
По подобию того как сделан вывод уникального идентификатора.

**Comment by Oleg1085** [comment]
А справка по макро колонкам есть в инструментах? а то я только через гугл нашел как ими пользоваться.
Сейчас же только УИД есть?

**Comment by LevkinSergey** [comment]
Нет. Хотя нужно. Я думал сделать контекстное меню, где это можно было бы быстро добавить. 
Сейчас только УИД.

**Comment by Oleg1085** [comment]
Если фичу добавляем в два инструмента куда поместить Функция ДатаСозданияСсылки(Ссылка) ? в Общий Модуль УИ_ОбщегоНазначения?

**Comment by LevkinSergey** [comment]
В общий модуль УИ_ОбщегоНазначенияКлиентСервер.
Вроде нет никаких особенностей, привязывающих исполнение только на сервере

**Comment by Oleg1085** [comment]
СмещениеСтандартногоВремени() и СмещениеЛетнегоВремени() - Доступность Сервер, толстый клиент, внешнее соединение, мобильное приложение (сервер), мобильный автономный сервер.

**Comment by LevkinSergey** [comment]
Тогда в УИ_ОбщегоНазначения
