### ISSUE TITLE
Время создания ссылки при разборе гуид в Редактор реквизитов

### ISSUE THREAD

**Issue by Untru** [cpr1c/tools_ui_1c#387]
# Описание задачи

**Можно ли в редактор объекта добавить информацию о дате создания ссылки, код обсуждался в чате

**Опишите решение**
  ГУИД = Ссылка.УникальныйИдентификатор();
  Строка16 = Сред(ГУИД, 16, 3) + Сред(ГУИД, 10, 4) + Сред(ГУИД, 1, 8);
  Разрядность = СтрДлина(Строка16);
  ЧислоСек = 0;
  Для Позиция = 1 По Разрядность Цикл
    ЧислоСек = ЧислоСек + Найти("123456789abcdef",Сред(Строка16,Позиция,1))*Pow(16,Разрядность - Позиция);
  КонецЦикла;
  ЧислоСек = ЧислоСек / 10000000;
  Сообщить(Дата(1582, 10, 15, 04, 00, 00) + ЧислоСек);
![image](https://user-images.githubusercontent.com/60393326/142618352-6a38db29-eeb7-4d08-b58d-b655d7b8d0c3.png)

**Comment by LevkinSergey** [comment]
Дубль с #381
