### ISSUE TITLE
В запросе не убирает символ переноса строк из запроса. |

### ISSUE THREAD

**Issue by nagaitseff** [cpr1c/tools_ui_1c#399]
При добавлении запроса из конфигуратора в консоль запросов и нажатии на команду "Убрать перенос строк из текста" появляется ошибка. Ошибка появляется независимо от того выделен текст запроса или нет

Метод объекта не обнаружен (ПолучитьГраницыВыделения)
{УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.Форма.Форма(3863)}:	ЭлементТекст.ПолучитьГраницыВыделения(НачальнаяСтрока, НачальнаяКолонка, КонечнаяСтрока, КонечнаяКолонка);
{УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.Форма.Форма(4246)}:	УстановитьГраницыВыделенияДляОбработкиСтрок(ЭлементТекст, НачальнаяСтрока, НачальнаяКолонка, КонечнаяСтрока,
{УниверсальныеИнструменты Обработка.УИ_КонсольЗапросов.Форма.Форма.Форма(4268)}:		УбратьПереносСтрокИзТекста(Элементы.ТекстЗапроса);

**Окружение**
 - Версия платформы: 8.3.18.1289
 - Серверная

**Comment by LevkinSergey** [comment]
Какой редактор кода используется?

**Comment by nagaitseff** [comment]
> 

Monako

**Comment by LevkinSergey** [comment]
ОШибку повторил.

**Comment by cosmo-sys** [comment]
Версия платформы 8.3.18.1289
![image](https://user-images.githubusercontent.com/11264900/150816522-61fcfae6-7f70-433a-a5f5-319bcf01bf2e.png)

**Comment by LevkinSergey** [comment]
Исправил в 1.4.13
