### ISSUE TITLE
Ошибка в консоли запросов при смене редактора кода на Ace

### ISSUE THREAD

**Issue by nagaitseff** [cpr1c/tools_ui_1c#404]
**Опишите ошибку**
Был открыт редактор кода Monaco, сменил на редактор кода Ace, при входе в консоль запросов - ошибка.
![2022-01-21_15-03-32](https://user-images.githubusercontent.com/32049603/150489919-bd28fa52-473e-4bc8-9c5c-e3edcbb0b79e.png)

**Comment by nagaitseff** [comment]
Инструменты установлены как расширение с БСП

**Comment by LevkinSergey** [comment]
Исправлено в версии 1.4.13
