### ISSUE TITLE
Ошибка в обработке УИ_КонсольHTTPЗапросов.epf

### ISSUE THREAD

**Issue by konstsv** [cpr1c/tools_ui_1c#409]
В модуле Формы обработки, в процедуре 
`&НаСервере`
`Функция ПодготовленныйЗапросHTTP(СтруктураURL)`
...
`СтрокаПараметров = "";`
`Для Каждого КлючЗначение Из СтруктураURL.ПараметрыЗапроса Цикл`

> `	СтрокаПараметров = СтрокаПараметров + ?(ЗначениеЗаполнено(СтрокаПараметров), "?", "&") + КлючЗначение.Ключ + "="`
> `		+ КлючЗначение.Значение;`
> 

`КонецЦикла;`

пропущен оператор **НЕ** перед `ЗначениеЗаполнено(СтрокаПараметров)`

**Comment by LevkinSergey** [comment]
Поправил. Спасибо
