### ISSUE TITLE
Расширение не собирается из исходников

### ISSUE THREAD

**Issue by petypen** [cpr1c/tools_ui_1c#41]
Добрый день.
Платформа 8.3.15 Разработка в конфигураторе.
Пытаюсь конфигурацию загрузить из файлов исходников (tools_ui_1c\Инструменты\src) получаю ошибку. См. скриншот.
![2020-01-15 11-44-48 Конфигуратор - Бухгалтерия предприятия, редакция 3 0](https://user-images.githubusercontent.com/6500075/72414809-84bab880-378c-11ea-9e1b-3f78a359db00.png)

**Comment by LevkinSergey** [comment]
Добрый день

Расширение разрабатывается в ЕДТ. Его формат отличается от формата выгрузки файлов конфигурации. 


На текущий момент два варианта:
1. Взять cfe  с закладки релизов и его загрузить
2. Импортировать проект в ЕДТ и оттуда грузануть в базу. Если нужно что-то доделать, то используйте ЕДТ
