### ISSUE TITLE
Не работает кнопка "Удалить" в обработке "Редактор реквизитов объекта база данных"

### ISSUE THREAD

**Issue by alekseineputin** [cpr1c/tools_ui_1c#416]
Не работает кнопка "Удалить" в обработке "Редактор реквизитов объекта база данных".

**Воспроизведение ошибки**
1. Запустить обработку  "Редактор реквизитов объекта база данных"
2. Выбрать любой справочник.
3. Выбрать любой элемент справочника.
4. Нажать кнопку "Удалить" и ответить утвердительно на следующее предупреждение.
5. Выбрать этот же элемент справочника.
6. Увидеть ошибку - элемент не удален.

**Ожидаемое поведение**
Объект должен быть удален.

**Окружение**
 - Версия платформы: 1С:Предприятие 8.3 (8.3.18.1289)
 - Режим базы данных(файловая/серверная/веб): серверная
 - Конфигурация: Бухгалтерия предприятия КОРП, редакция 3.0
 - Версия конфигурации: 3.0.106.60
 - ОС: Windows Server 2019 Standart
 - Версия: 2019
 

**Дополнительная информация**

**Comment by arimefu** [comment]
Необходимо в обработке "УИ_РедакторРеквизитовОбъекта" в форме "ФормаОбъекта" в серверной функции "вУдалитьОбъектНаСервере" там, где происходит запись объекта добавить третий аргумент "Непосредственное удаление" (строка 855):

`Если УИ_ГЕНЕРАЦИЯ_ОбщийМодульПоИмени("УИ_ОбщегоНазначения").ЗаписатьОбъектВБазу(пОбъект, УИ_ГЕНЕРАЦИЯ_ОбщийМодульПоИмени("УИ_ОбщегоНазначенияКлиентСервер").ПараметрыЗаписиФормы(
			ЭтаФорма)) Тогда`
заменить на:
`Если УИ_ГЕНЕРАЦИЯ_ОбщийМодульПоИмени("УИ_ОбщегоНазначения").ЗаписатьОбъектВБазу(пОбъект, УИ_ГЕНЕРАЦИЯ_ОбщийМодульПоИмени("УИ_ОбщегоНазначенияКлиентСервер").ПараметрыЗаписиФормы(
			ЭтаФорма), "НепосредственноеУдаление") Тогда`

**Comment by VoronyukM** [comment]
Прошу принять PR, в котором это исправлено

**Comment by alekseineputin** [comment]
Здравствуйте.
 
А как это сделать?

**Comment by LevkinSergey** [comment]
Я уже принял
