### ISSUE TITLE
2 вариант поля заголовков

### ISSUE THREAD

**Issue by dzottula** [cpr1c/tools_ui_1c#42]
предлагаю сделать галочку, что бы можно было пользоваться обоими вариантами: как текстовое поле и как таблица из двух колонок. В текстовое поле удобно копировать из других источников, а в таблице удобно набирать заголовки. Первая колонка должна быть справочником ( что бы не переписывать название заголовка каждый раз,  и что бы выдавала наиболее вероятный заголовок в первую очередь). Можно так же сделать кнопку "Скопировать заголовок", по нажатию на которую, будет предложен список последних заполненных заголовков, что бы выбрать из них нужный.

**Comment by LevkinSergey** [comment]
я думал сделать что-то типа предопределенных заголовков для разных ситуаций.
и разместить где-то тут 
![image](https://user-images.githubusercontent.com/36307272/72415999-c8aabf00-3786-11ea-8d7a-f74d5d638176.png)

> Первая колонка должна быть справочником ( что бы не переписывать название заголовка каждый раз, и что бы выдавала наиболее вероятный заголовок в первую очередь). 

Какой предполагаешь алгоритм определения наиболее вероятного заголовка?

**Comment by dzottula** [comment]
ну опять же варианта два. если это справочник, то система сама будет подсовывать последние использовавшиеся варианты. ну а либо запросом,  скажем, выбирать "топ 5" из истории запросов (если она есть). В общем я то склоняюсь к первому варианту

**Comment by LevkinSergey** [comment]
Сделал редактирование заголовков и строкой и таблицей. Сделал переключатель
![image](https://user-images.githubusercontent.com/36307272/72434624-218d4e00-37ad-11ea-80e3-730ffe5f04da.png)

При добавлении нового заголовка реализована автоподбор заголовка из ранее использованных в истории запросов
![image](https://user-images.githubusercontent.com/36307272/72434676-42ee3a00-37ad-11ea-9d1c-7cd4a460a391.png)
