### ISSUE TITLE
Отладка Запроса в транзакции. Отладочные данные не сохраняются при отмене транзакции.

### ISSUE THREAD

**Issue by puretruth** [cpr1c/tools_ui_1c#428]
**Опишите ошибку**
При вызове отладки запроса, выполняющегося в транзакции. В случае, если транзакция откатывается, то отладочные данные не сохраняются.

**Воспроизведение ошибки**
1. Написать любой запрос в транзакции, поставить точку останова, запустить отладку.
2. Вызвать в отладке УИ_._ОТ(Запрос), продолжить выполнение программы
3. Открыть справочник "Данные для отладки", чтобы убедиться, что данных для отладки не добавилось.

**Ожидаемое поведение**
Ожидается, что данные для отладки будут сохранены.

**Окружение**
 - Версия платформы: 8.3.19
 - Режим базы данных(файловая/серверная/веб): серверная
 - Конфигурация: УХ
 - ОС: Windows
 

**Дополнительная информация**
Предполагаю, что в данном случае хорошим вариантом будет предоставить возможность выбора расположения сохранения отладочных данных - в справочник или файл. Или как вариант проверять ТранзакцияАктивна(), и в зависимости от этого принимать решение о сохранении. Однако, в любом случае придётся добавить команду получения отладочных данных из файла.
Если данные сохраняются в файл, то при откате транзакции, есть возможность их получить в дальнейшем для отладки.
Так реализовано в исходной версии консоли запросов 9000
https://github.com/hal9000cc/RequestConsole9000

**Comment by LevkinSergey** [comment]
Я думал сделать еще один метод _ОтФ, который бы записывал файл в папку инструментов на сервере. А дальше добавить чтение данных отладки из папки, а также удаление и т.п.
Еще был вариант чтобы дать возможность указывать местонахождение файла. Но это усложняет использование

Еще вариант был в функции _От реализовать запись через фоновое задание
