### ISSUE TITLE
Возможность выбора ссылок на объекты расширений (обработка ПоискСсылокНаОбъект)

### ISSUE THREAD

**Issue by CoolPirat** [cpr1c/tools_ui_1c#435]
В обработке ПоискСсылокНаОбъект отсутствует возможность выбора ссылок на объекты расширений. 

Данная возможность реализована в обработке РедакторРеквизитовОбъекта (реализация с помощью формы "УИ_ФормаВыбораТипаОбъекта")

**Comment by LevkinSergey** [comment]
реализовано
