### ISSUE TITLE
Ошибка при синхронизации Бухгалтерии с ЗУПОМ (отключил расширение в Бухгалтерии и заработало нормально).

### ISSUE THREAD

**Issue by FominAV** [cpr1c/tools_ui_1c#44]
![15-01-2020 13-18-15](https://user-images.githubusercontent.com/59277563/72432546-5ea31180-37a8-11ea-8bcc-3fc12c3f1fd9.png)

**Comment by LevkinSergey** [comment]
судя по всему проблема с использовании переменной УИ в стандартной конфигурации.
![image](https://user-images.githubusercontent.com/36307272/72434891-cd369e00-37ad-11ea-9e3b-9ccf568a0cdd.png)

Придется переименовать модуль для вызова отладки

**Comment by LevkinSergey** [comment]
исправлено в релизе 1.3.0
