### ISSUE TITLE
В редакторе кода не открывается конструктор запроса для текущего запроса.

### ISSUE THREAD

**Issue by BProg-Gladkov** [cpr1c/tools_ui_1c#447]
**Воспроизведение ошибки**
1. Запустить обработку "Консоль кода"
2. Написать код в котором есть запрос.
3. Попробовать открыть конструктор запроса.
Появится предложение создать новый текст запроса.
![image](https://user-images.githubusercontent.com/33430119/172163882-ac874459-6aa3-48a1-b194-3e636e738ec1.png)

**Ожидаемое поведение**
Откроется конструктор запроса для редактирования текущего запроса.

 - Версия: 1.4.13

**Comment by LevkinSergey** [comment]
Ошибку повторил.

**Comment by LevkinSergey** [comment]
ИСправлено в тестовой версии. Просьба проверить на вашем оборудовании

**Comment by BProg-Gladkov** [comment]
> ИСправлено в тестовой версии. Просьба проверить на вашем оборудовании

Проверил, работает, спасибо.
