### ISSUE TITLE
Ошибка при изменении видимости элемента редактора кода

### ISSUE THREAD

**Issue by BProg-Gladkov** [cpr1c/tools_ui_1c#448]
**Воспроизведение ошибки**
1. Создать обработку в котором видимость редактора кода изменяется.
2. Нажать на кнопку, которая выполнит "Элементы.РедакторКода.Видимость = Ложь"
3. Появится ошибка:
Значение не является значением объектного типа (defaultView)
{УниверсальныеИнструменты ОбщийМодуль.УИ_РедакторКодаКлиент.Модуль(111)}:ДокументView = ЭлементФормыРедактора.Документ.defaultView;
{УниверсальныеИнструменты ОбщийМодуль.УИ_РедакторКодаКлиент.Модуль(192)}:ИнициализироватьРедаторыФормыПослеФормированияПолей(Форма, РедакторыФормы, ВидРедактора, ВидыРедактора);

**Ожидаемое поведение**
Подключаю редактор фор к своим формам.
По логике работы формы надо возможность скрывать поле редактора.

**Comment by LevkinSergey** [comment]
Планиурется ли многократное переключение видимости?

**Comment by BProg-Gladkov** [comment]
> Планиурется ли многократное переключение видимости?

Да, планируется.

**Comment by LevkinSergey** [comment]
С версией из develop повторить ошибку не удалось. Можете приложить вашу тестовую обработку или код инициализации

**Comment by LevkinSergey** [comment]
Повторил, если несколько редакторов и при включении есть хотя бы один невидимый.

**Comment by LevkinSergey** [comment]
Реализовано в тестовой версии. Добавил два новых метода для управления видимостью редактора кода

```bsl
// Устанавливает новую видимость для редактора кода по идентификатору редактора
// Если передан параметр "НоваяВидимость", то устанавливается заданная видимость.
// Если параметр "НоваяВидимость" не указан, происходит переключение видимости редактора
// 
// Параметры:
//  Форма - ФормаКлиентскогоПриложения -
//  ИдентификаторРедактора - Строка - Идентификатор редактора
//  НоваяВидимость -  Булево - Новая видимость элемента редактора. Необязательный. 
Процедура ПереключитьВидимостьРедактора(Форма, ИдентификаторРедактора, НоваяВидимость = Неопределено) Экспорт

```

```bsl
// Устанавливает новую видимость для редактора кода по элементу формы редактора
// Если передан параметр "НоваяВидимость", то устанавливается заданная видимость.
// Если параметр "НоваяВидимость" не указан, происходит переключение видимости редактора
// 
// Параметры:
//  Форма - ФормаКлиентскогоПриложения -
//  Элемент - ПолеФормы - Элемент формы редактора
//  НоваяВидимость -  Булево - Новая видимость элемента редактора. Необязательный. 
Процедура ПереключитьВидимостьРедактораЭлементаФормы(Форма, Элемент, НоваяВидимость = Неопределено) Экспорт

```

**Comment by BProg-Gladkov** [comment]
> ```bsl
> ПереключитьВидимостьРедактораЭлементаФормы
> ```

После переключения видимости очистилось содержимое редактора кода.
Сценарий воспроизведения:
1. Набрал кода.
2. Видимость = Ложь
3. Видимость = Истина
Кода нет.

**Comment by LevkinSergey** [comment]
Исправил. Также поправил ошибку многократного вызова события формы при переключении видимости Подключаемый_РедакторКодаЗавершениеИнициализации()

Теперь это событие будет вызываться однократно
