### ISSUE TITLE
Консоль запросов. Ошибка при установке параметра запроса тип СписокЗначений

### ISSUE THREAD

**Issue by fanil1s** [cpr1c/tools_ui_1c#455]
При попытке указать значение параметра с типом контейнера СписокЗначений или Массив, получаю такую ошибку, текущая версия портативных инструментов 1.4.14, на 11 версии тоже самое

https://prnt.sc/Cv7avgP0u1hM

Преобразование значения к типу Число не может быть выполнено
{ВнешняяОбработка.УИ_КонсольЗапросов.МодульОбъекта(1472)}:		Результат = Результат + Разделитель + Строки[сч];
{ВнешняяОбработка.УИ_КонсольЗапросов.МодульОбъекта(1120)}:			Возврат Лев(_СтрСоединить(Контейнер.СписокЗначений.ВыгрузитьЗначения(), "; "), чРазмерПредставления);
{ВнешняяОбработка.УИ_КонсольЗапросов.МодульОбъекта(1071)}:		Результат.Представление = Контейнер_ПолучитьПредставление(Результат);
{ВнешняяОбработка.УИ_КонсольЗапросов.Форма.ПодборВСписок.Форма(59)}:	Возврат РеквизитФормыВЗначение("Объект").Контейнер_СохранитьЗначение(СписокЭлементов);
{ВнешняяОбработка.УИ_КонсольЗапросов.Форма.ПодборВСписок.Форма(66)}:	ВозвращаемоеЗначение = Новый Структура("Значение", ПолучитьВозвращаемоеЗначение());

Платформа: 1С:Предприятие 8.3 (8.3.18.1741)
Конфигурация: Управление торговлей, редакция 11 (11.4.14.181) (http://v8.1c.ru/trade/)
Copyright © ООО "1С-Софт", 2003-2018. Все права защищены
(http://www.1c.ru)

Режим: Серверный (сжатие: усиленное)
Приложение: Тонкий клиент
Локализация: Информационная база: русский (Россия), Сеанс: русский
Вариант интерфейса: Такси

**Comment by fanil1s** [comment]
Исправленный текст функции модуля объекта обработки УИ_КонсольЗапросов

Функция _СтрСоединить(Строки, знач Разделитель = Неопределено) Экспорт
	Результат = "";
	
	Если Разделитель = Неопределено Тогда
		Разделитель = "";
	КонецЕсли;
	
	Если Строки.Количество() Тогда
		Результат = Строка(Строки[0]); //исправление -приведение к типу Строка
	КонецЕсли;
	
	Для сч = 1 По Строки.ВГраница() Цикл
		Результат = Результат + Разделитель + Строки[сч];
	КонецЦикла;
	
	Возврат Результат;
КонецФункции

**Comment by LevkinSergey** [comment]
очень странно, что в 1.4.14 появляется. В ней вроде исправлял этот баг. Проверю
