### ISSUE TITLE
Консоль запросов сообщение об ошибке "Метод объекта не обнаружен (GetText)"

### ISSUE THREAD

**Issue by VladimirChi** [cpr1c/tools_ui_1c#458]
**Опишите ошибку**
При многопользовательской работе на сервере терминалов в консоли запросов возникает окно ошибки "Метод объекта не обнаружен (GetText)". При закрытии консоли и всей внешней обработки возникает еще одно окно с сообщением об ошибке "Ошибка доступа к файлу "/tmp/tools_ui_1c/1.4.13/Monaco/editor.zip". 13(0x0000000D): Отказано в доступе". Исследование показало, что папка и файлы созданы другими пользователями и не доступны для изменения/удаления другим пользователям и это правильно. 

**Воспроизведение ошибки**
1. Запустить внешнюю обработку
2. Запустить консоль запросов
3. Увидеть ошибку. Важно, что бы под другим пользователем также уже было открыто.

**Ожидаемое поведение**
Важно, что бы у каждого пользователя была своя личная временная папка, для разворачивания необходимых компонент. Хотя бы уникальная. В этом случае таких проблем возникать не должно

**Окружение**
 - OS: Астра-Линукс 1.6
 - Версия платформы: 8.3.17
 - Режим базы данных: серверная
 - Конфигурация: самописная
 - Режим работы: внешная компонента

**Comment by LevkinSergey** [comment]
Повторил на linux mint.

**Comment by LevkinSergey** [comment]
Нужно сохранять Компоненты в РабочийКаталогДанныхПользователя. 
Он и в линуксе и в винде в каталоге пользователя создается
