### ISSUE TITLE
Редактор констант

### ISSUE THREAD

**Issue by Danilov-5880** [cpr1c/tools_ui_1c#460]
**Опишите ошибку**
- Универсальные инструменты (1.4.12)
Не изменяет константу с типом данных 'хранилище значений'
если выполнить код в  консоле кода:
Путь1="\\SRV-1C01\exchanges\Fox\TEST" ;

	Структура = Новый Структура("Путь1", Путь1);
	Константа = Константы.Чд_ПутиВыгрузкиВDBFПоПлановымДатам.СоздатьМенеджерЗначения();
	Константа.Значение = Новый ХранилищеЗначения(Структура);
	Константа.Записать();
                               
      К=Константы.Чд_ПутиВыгрузкиВDBFПоПлановымДатам.Получить().Получить()  ;   
Сообщить(К.Путь1);    
все хорошо отрабатывает 
**Ожидаемое поведение**
Редактировать константу с типом данных 'хранилище значений' через интерфейс редактора констант
**Окружение**
 1С:Предприятие 8.3 (8.3.20.1996)
серверная

 - Версия конфигурации:
 - ОС: 
 - Версия:
 

**Дополнительная информация**
Может чего подскажите ))) А так очень удобное расширение !!!!

**Comment by dyevgeniy** [comment]
Подтверждаю, есть такая особенность

**Comment by leemuar** [comment]
Что вы храните в константе с типом "Хранилище значений"? Файлы? И как вы хотите чтобы это можно было редактировать? Приведите пример

**Comment by dyevgeniy** [comment]
Пример: конфигурация Бухгалтерия предприятия. В константах есть СведенияОбОбновленииИБ, тип Хранилище значений, внутри нее мне нужно было поменять значение ВерсияУдаленияПатчей 
Скрин: https://cloud.mail.ru/public/stsi/kRMQCqCDZ

**Comment by free-archer** [comment]
Ошибка возникала в случае если в хранилище значений хранится ,например, массив в котором значения есть хранилища значений.

Попробую обработать такую ситуацию.
