### ISSUE TITLE
Задание наименования для объекта отладки

### ISSUE THREAD

**Issue by Untru** [cpr1c/tools_ui_1c#467]
# Описание задачи
Когда часто пользуешься функцией УИ_._От() в базе копятся настройки в которых сложно ориентироваться, было бы удобно что бы была возможность назначать имена 

![image](https://user-images.githubusercontent.com/60393326/198240950-44e44117-10e2-4ec1-98d8-696fb357990f.png)

**Comment by LevkinSergey** [comment]
у меня два варинта пока

- добавить дополнительный параметр в метод УИ_._ОТ
- Как-то автоматически генерировать наименование. 

По автоматическому наименованию для отладки ссылки, HTTP запросов, можно сформировать, По запросам, СКД и др. если есть мысли, поделись

**Comment by Untru** [comment]
Для ссылок, тут да понятно, вопрос с запросами, и у меня достаточно узкий кейс, есть код в котором n количество запросов, и при включенном флаге отладки у меня прямо в коде написано УИ_._ОТ. на выходе я получаю список этих записей, пойди найди где есть что =) , по этому для меня дополнительный не обязательный параметр в тему.... 
Ну и автоматически никак запрос не назвать, у нас по сути только параметры, текст и МВТ, тут даже разбор текста через схему запросов наверно мало чем поможет... время добавления и так есть, по этому да, я вижу только доп параметр.

**Comment by Xolodec1984** [comment]
@LevkinSergey могу попробовать выполнить задачу? Переведите ее на меня.

**Comment by Xolodec1984** [comment]
@LevkinSergey, вопрос, этот репозиторий содержит не проект EDT? пытаюсь его подключить не могу разобраться. Подскажи как внести правки?

**Comment by LevkinSergey** [comment]
> @LevkinSergey, вопрос, этот репозиторий содержит не проект EDT? пытаюсь его подключить не могу разобраться. Подскажи как внести правки?

Вот тут смотрел?
https://github.com/cpr1c/tools_ui_1c/tree/develop/docs/contributing

**Comment by Xolodec1984** [comment]
@LevkinSergey  Информацию увидел. Буду подключаться.
