### ISSUE TITLE
Пожелание по формированю текста запроса для конфигуратора

### ISSUE THREAD

**Issue by borisovcpr** [cpr1c/tools_ui_1c#47]
Скрин:

http://joxi.ru/DmBgVRqIzgZNa2

1. Добавлять в текст установку параметров из текста запроса
Запрос.УстановитьПараметр("ИмяПараметра", Неопределено);

2. Не делать отступ текста запроса по отношению к остальному тексту

3. Не переносить ; на следующую строку.

**Comment by LevkinSergey** [comment]
Исправлено в ветке develop
