### ISSUE TITLE
Не загружаются настройки в консоль http запросов

### ISSUE THREAD

**Issue by Oleg1085** [cpr1c/tools_ui_1c#472]
**Опишите ошибку**
Не загружаются настройки в консоль http запросов

**Воспроизведение ошибки**
1. Запустил обработку "консоль http запросов"
2. Нажал файл - открыть. выбрал ранее сохраненный файл с расширением "jhttp"
3. И ничего не происходит

**Ожидаемое поведение**
Должны загрузиться сохраненные запросы.

**Окружение**
    Версия платформы: 8.3.18.1779
    Режим базы данных - файловая
    Конфигурация БСП Демо
    Версия конфигурации: 3.1.5
    ОС: Win 10

**Comment by cosmo-sys** [comment]
Решение: 
В модуле менеджера обработки "УИ_КонсольHTTPЗапросов" в функции "ДанныеСохраненияИзСериализованнойСтроки" в строке "ТекстовыйДокумент.Прочитать" добавляем принудительное использование кодировки UTF8 ТекстовыйДокумент.Прочитать(ДанныеФайла.ОткрытьПотокДляЧтения(), КодировкаТекста.UTF8);
Настройки сохраняются и открываются без проблем.
