### ISSUE TITLE
Ошибка при отладке СКД в портативных инструментах

### ISSUE THREAD

**Issue by denk-32** [cpr1c/tools_ui_1c#475]
**Опишите ошибку**
При нажатии кнопки "Отладить" в обработке "Данные для отладки" выходит ошибка:
Неизвестное имя формы "ВнешняяОбработка.УИ_КонсольОтчетов.Форма"

**Воспроизведение ошибки**
1. Поставить точку останову при выполнении отчета на СКД
2. Выполнить метод ВнешниеОбработки.Создать("УИ_")._От(СистемаКомновкиДанных, НастройкиСКД)
3. В обработке "Данные для отладки" нажать кнопку "Отладить"

**Ожидаемое поведение**
Ошибка не должна выходить. Должна открываться консоль отчетов.
В обработке УИ_ОбщегоНазначенияКлиент.epf в модуле формы, в строке 232 необходимо заменить:
ИмяФормыКонсоли = "ВнешняяОбработка.УИ_КонсольОтчетов.Форма";
на
ИмяФормыКонсоли = "ВнешнийОтчет.УИ_КонсольОтчетов.Форма";

**Окружение**
 - Версия платформы: 8.3.19.1264
 - Режим базы данных(файловая/серверная/веб): Cерверная
 - Конфигурация: Документооборот 8 КОРП, редакция 2.1
 - Версия конфигурации: 2.1.25.5
 - ОС: Windows
 - Версия: 10
 

**Дополнительная информация**

**Comment by LevkinSergey** [comment]
ИСправлено в новой версии
