### ISSUE TITLE
Консоль запросов: при удалении всех уровней упорядочивания через конструктор АВТОУПОРЯДОЧИВАНИЕ не отключается автоматически

### ISSUE THREAD

**Issue by GlebHappy** [cpr1c/tools_ui_1c#477]
**Консоль запросов: при удалении всех уровней упорядочивания через конструктор АВТОУПОРЯДОЧИВАНИЕ не отключается автоматически**

**Воспроизведение ошибки**
1. Создаем через конструктор запрос с упорядочивание и ставим флажок "Автоупорядочивание"
2. Выполняем
3. Через конструктор убираем ярусы упорядочивания
4. В запросе конструкция `УПОРЯДОЧИТЬ ПО` удаляется автоматически, а вот `АВТОУПОРЯДОЧИВАНИЕ` остается

**Comment by LevkinSergey** [comment]
Запиши, пожалуйста, видео как это получается
