### ISSUE TITLE
Не отправляется на гитхаб задача из формы расширения

### ISSUE THREAD

**Issue by borisovcpr** [cpr1c/tools_ui_1c#48]
![image](https://user-images.githubusercontent.com/36307480/72602441-583ba380-3928-11ea-80e4-2fcfc7e93d9f.png)
![image](https://user-images.githubusercontent.com/36307480/72602475-65589280-3928-11ea-9633-85afedaf56da.png)

**Comment by LevkinSergey** [comment]
Исправил в develop ветке
