### ISSUE TITLE
Очищаются поля в консоле запросов

### ISSUE THREAD

**Issue by Oleg1085** [cpr1c/tools_ui_1c#481]
**Опишите ошибку**
Очищаются поля Алгоритм перед выполнением и Обработка результата в консоле запросов.

**Воспроизведение ошибки**
1. Открыть консоль запросов
2. Написать текст запроса и Алгоритм перед выполнением.
3. Нажать Выполнить, увидеть что все работает как надо
4. Нажать кнопку Параметры
5. Увидеть что поле Алгоритм перед выполнением пустое
Тоже самое и с полем Обработка результата

**Ожидаемое поведение**
Поля не должны очищаться

**Окружение**
 - Версия платформы: 8.3.20.1996
 - Режим базы данных - файловая
 - Конфигурация: БСП демо 
 - Версия конфигурации: 3.1.5
 - ОС: Win 10 x64

**Comment by LevkinSergey** [comment]
Какая версия инструментов?
Какой редактор кода установлен в настройках?

**Comment by Oleg1085** [comment]
Версия инструментов 1.4.14 - расширение.
