### ISSUE TITLE
Консоль запросов, Конструктор, версия 1.4.14

### ISSUE THREAD

**Issue by Shulepov-Aleksandr** [cpr1c/tools_ui_1c#482]
# Описание задачи
в последней версии на сегодня 1.4.14
на платформе 1С:Предприятие 8.3 (8.3.18.1616)
открыть консоль запросов - Конструктор - кнопка "Запрос"
если текст запроса пустой, выдаст ошибку с перезагрузкой программы

**Опишите вашу Цель, которую вы сможете достичь с помощью новой функциональности**
стабильность работы консоли запросов

**Опишите решение**
у меня решения нет.
возможное предположение: учитывать версию платформы.

**Дополнительная информация**
УИ_КонсольЗапросов.epf(Форма) 745 
стрТекстЗапроса = ТекущийТекстЗапроса();

Если стрТекстЗапроса = "" то ошибка

**Comment by LevkinSergey** [comment]
Повторить не удалось. Пробовал на 22, 23. Есть возможность проверить на этой?
[Portable.zip](https://github.com/cpr1c/tools_ui_1c/files/11582018/Portable.zip)

**Comment by Shulepov-Aleksandr** [comment]
1с 8.3.20.2184, tools_ui_1c v23.6.1
всё работает
