### ISSUE TITLE
Редактор движений документов

### ISSUE THREAD

**Issue by Chuwashov** [cpr1c/tools_ui_1c#483]
**Опишите ошибку**

При попытке отредактировать записи движений документа не возможно выбрать регистр, в котором хотел отредактировать записи. 

**Воспроизведение ошибки**
1. Редактор реквизитов объекта базы данных
2. Выбор объекта ИБ (Выбирал документ реализация товаров и услуг)
3. Выбрал документ из списка
4. Переход на вкладку движения 
5. Переход в редактор движений по кнопке
6. При попытке выбора записи из таблицы "Движения документа" выдается ошибка поле объекта не обнаружено (Пример регитр накопления себестоимость товаров. Подобная ошибка появляется после выбора любого другого регистра) 
![Screenshot_3](https://user-images.githubusercontent.com/62375911/206484425-88a05825-5a8a-4fe3-b555-6c99562335d9.png)

**Ожидаемое поведение**
После описанных выше действий должна заполняться таблица "Редактор набора записей".

**Окружение**
 - Версия платформы: 8.3.19.1726
 - Режим базы данных(файловая/серверная/веб): Серверный (сжатие: усиленное)
 - Конфигурация: Управление торговлей, редакция 11
 - Версия конфигурации: 11.5.7.402
 - ОС: Windows 10 Pro

**Comment by free-archer** [comment]
В конфигурации БСП ошибка не воспроизводится.
В УТ 11.5.7.383 2 ошибки подряд.

`"applicationErrorInfo": {
			"errors": [
				[
					"{УниверсальныеИнструменты Обработка.УИ_РедакторРеквизитовОбъекта.Форма.ФормаРедакторДвижений.Форма(735)}: Поле объекта не обнаружено (Стр_РегистрНакопления_ВыручкаИСебестоимостьПродаж)",
					[
						"ScriptRuntimeError",
						"ScriptUseError"
					],
					"",
					""
				]
			],
			"stack": [
				[
					"УниверсальныеИнструменты Обработка.УИ_РедакторРеквизитовОбъекта.Форма.ФормаРедакторДвижений.Форма",
					735,
					"\u0009\u0009\u0009Элементы.СтраницыНаборыЗаписей.ТекущаяСтраница = Элементы[\"Стр_\" + ИмяРеквизита];"
				]
			],`

`		"applicationErrorInfo": {
			"errors": [
				[
					"{УниверсальныеИнструменты Обработка.УИ_РедакторРеквизитовОбъекта.Форма.ФормаРедакторДвижений.Форма(589)}: Ошибка при вызове метода контекста (ИзменитьРеквизиты)",
					[
						"ScriptRuntimeError"
					],
					"",
					""
				],
				[
					"",
					[],
					"",
					""
				],
				[
					"Неуникальное имя реквизита. Имя: \"РегистрНакопления_ДвиженияПоПрочимАктивамПассивам\"",
					[],
					"",
					""
				]
			],
			"stack": [
				[
					"УниверсальныеИнструменты Обработка.УИ_РедакторРеквизитовОбъекта.Форма.ФормаРедакторДвижений.Форма",
					76,
					"\u0009_Обновить(Неопределено);"
				],
				[
					"УниверсальныеИнструменты Обработка.УИ_РедакторРеквизитовОбъекта.Форма.ФормаРедакторДвижений.Форма",
					125,
					"\u0009вОбновить();"
				],
				[
					"УниверсальныеИнструменты Обработка.УИ_РедакторРеквизитовОбъекта.Форма.ФормаРедакторДвижений.Форма",
					698,
					"\u0009вСоздатьРеквизитыНаборовЗаписей(НадоСоздаватьРеквизиты);"
				],
				[
					"УниверсальныеИнструменты Обработка.УИ_РедакторРеквизитовОбъекта.Форма.ФормаРедакторДвижений.Форма",
					589,
					"\u0009\u0009ИзменитьРеквизиты(МассивКСозданию, МассивКУдалению);"
				]
			],`

**Comment by free-archer** [comment]
Почему то в движениях встречается 2 строчки по регистру:

![image](https://github.com/cpr1c/tools_ui_1c/assets/36464371/cbdc8867-ef0a-4e04-8b0e-73168d847ef7)

Возможно стоит добавить проверку и пропустить вторую строку?
