### ISSUE TITLE
Регистрация изменений для обмена данными не дает выбрать узел из расширения.

### ISSUE THREAD

**Issue by Oleg1085** [cpr1c/tools_ui_1c#484]
**Опишите ошибку**
Регистрация изменений для обмена данными не дает выбрать узел из расширения.

**Воспроизведение ошибки**
1. Регистрация изменений для обмена данными
2. Нажать кнопку выбора Узла обмена
3. Выбрать узел плана обмена из расширения
4. Нажать выбрать.
5. Ничего не происходит
![изображение](https://user-images.githubusercontent.com/64373132/206719588-8bde8d1a-b9d9-412d-a07b-535421add922.png)

**Дополнительная информация**
Инструменты версия 1.4.14 - расширение

**Comment by nick-ez** [comment]
Тоже с этим столкнулся.
