### ISSUE TITLE
Ошибка в обработке "Групповая Обработка Справочников и Документов"

### ISSUE THREAD

**Issue by Oleg1085** [cpr1c/tools_ui_1c#488]
**Опишите ошибку**
В обработке "Групповая Обработка Справочников и Документов" при нажатии на кнопку "Выполнить" появляется ошибка 
`Недостаточно фактических параметров
{УниверсальныеИнструменты Обработка.УИ_ГрупповаяОбработкаСправочниковИДокументов.Форма.ПодборИОбработка.Форма(416)}:Обработка.ВыполнитьОбработку();
`

**Воспроизведение ошибки**
1. Запустить обработку "Групповая Обработка Справочников и Документов"
2. Заполнить на стройки на вкладках "Выбранные объекты" и "Найденные объекты"
3. На вкладке "Обработки" добавить обработку "Пометить на удаление"
4. Нажать "Выполнить" и увидеть ошибку.

**Ожидаемое поведение**
Должно работать без ошибок )))

**Окружение**
 - Версия платформы: 8.3.20.1996
 - Режим базы данных(файловая/серверная/веб): Файловая
 - Конфигурация: БСП Демо 3.1.5
 - ОС:  Win 10
 
**Дополнительная информация**
Инструменты - расширение, версия 1.4.14

**Comment by cosmo-sys** [comment]
Ошибка воспроизводится на релизе 1.4.14.  
Если использовать исправление от #https://github.com/Oleg1085/tools_ui_1c/commit/d34369da3a83c3e3d43a32a29241d0a9828af2e3
проблема с "Пометить на удаление" уходит, но возникает ошибка  с обработкой "ПроизвольныйАлгоритм".

Решение:
```
Если ИмяФормыОбработки = "ПроизвольныйАлгоритм" Тогда
	Обработка.ВыполнитьОбработку();
Иначе
	ПараметрыЗаписиОбъектов = УИ_ОбщегоНазначенияКлиентСервер.ПараметрыЗаписиФормы(ЭтотОбъект);
	Обработка.ВыполнитьОбработку(ПараметрыЗаписиОбъектов);
КонецЕсли;
```
![image](https://user-images.githubusercontent.com/11264900/235351770-e2b9df28-c290-401f-90dd-bad39c919982.png)
