### ISSUE TITLE
После обновления базовой конфигурации, под пользователями с ограниченными правами перезапускает клиента

### ISSUE THREAD

**Issue by mrshadow300373** [cpr1c/tools_ui_1c#491]
**Опишите ошибку**
Под пользователем с ограниченными правами перезапускает клиента после обновления базовой конфигурации, что приводит к массовому падению тестов из за того, что менеджер тестирования "теряет" клиента.

**Воспроизведение ошибки**
1. Обновить базовую конфигурацию, чтобы изменились роли пользователей
2. Запустить под пользователем с ограниченными правами
3. Клиент перезапуститься

**Ожидаемое поведение**
Если включен режим ОтключитьЛогикуНачалаРаботыСистемы (используется при тестировании) не перезапускать пользователя безусловно, как вариант выводить сообщение о необходимости перезапуска в сообщениях

**Окружение**
 - Версия платформы: 8.3..... неважно
 - Режим базы данных(файловая/серверная/веб): неважно
 - Конфигурация: любая
 - Версия конфигурации:
 - ОС: любая 
 - Версия: любая

**Дополнительная информация**
```
Процедура ПриНачалеРаботыСистемы() Экспорт
    ПараметрыСтартаСеанса=УИ_ОбщегоНазначенияВызовСервера.ПараметрыСтартаСеанса();

    Если ПараметрыСтартаСеанса.ДобавленыПраваНаРасширение Тогда
        ЗавершитьРаботуСистемы(Ложь, Истина);
    КонецЕсли;
```

**Comment by LevkinSergey** [comment]
Исправлено в новой версии.

**Comment by LevkinSergey** [comment]
Такое поведение замечено на новых БСП
