### ISSUE TITLE
Перезапуск клиента в конфигурациях с БСП

### ISSUE THREAD

**Issue by ITmind** [cpr1c/tools_ui_1c#498]
**Опишите ошибку**
1. При запуске конфигурации со встроенной БСП под пользователем с ролью ПолныеПрава из конфигуратора происходит перезапуск клиента и отладчик отключается.
2. При запуске конфигурации со встроенной БСП под пользователем с ролью ПолныеПрава в клиентском режиме выходит сообщение, что права изменены и требуется перезапуск

**Воспроизведение ошибки**
Запустить конфигурацию из конфигуратора под полными правами.

**Окружение**
Любая конфигурация с БСП 3.1.х 
 
**Дополнительная информация**
Проблема в том, что в БСП, если стоит роль "ПолныеПрава", то остальные роли у пользователя удаляются.
Следовательно УИ сначала добавляет роль, перезапускает клиента, а затем БСП удаляет роль и все заново, постоянный перезапуск. (иногда правда, если быстро жать запуск, можно избежать перезапуска )

**Решение**
В модуле УИ_ОбщегоНазначенияВызовСервера, в функции ПараметрыСтартаСеанса() добавить проверку на БСП.
Самый простой вариант проверить на название и доступность роли "ПолныеПрава".

```
Если Не УИ_ОбщегоНазначенияКлиентСервер.ЭтоПортативнаяПоставка() Тогда  
	//ИЗМ+
	ЕстьБСП = Метаданные.Роли.Найти("ПолныеПрава") <> неопределено И РольДоступна("ПолныеПрава");
	
	//@skip-check using-isinrole
	Если НЕ ЕстьБСП
        //ИЗМ-
		И ПравоДоступа("Администрирование", Метаданные) 
		И Не РольДоступна("УИ_УниверсальныеИнструменты")
		И ПользователиИнформационнойБазы.ПолучитьПользователей().Количество() > 0 Тогда  
		
		ТекущийПользователь = ПользователиИнформационнойБазы.ТекущийПользователь();
		ТекущийПользователь.Роли.Добавить(Метаданные.Роли.УИ_УниверсальныеИнструменты);
		ТекущийПользователь.Записать();
		ПараметрыСтартаСеанса.Вставить("ДобавленыПраваНаРасширение", Истина);
	Иначе
		ПараметрыСтартаСеанса.Вставить("ДобавленыПраваНаРасширение", Ложь);
	КонецЕсли;
Иначе
	ПараметрыСтартаСеанса.Вставить("ДобавленыПраваНаРасширение", Ложь);	
КонецЕсли;
```
Либо вообще убрать автоназначение роли, разработчик сам решит кому давать роль.

**Comment by LevkinSergey** [comment]
Такое поведение на БСП 3.1.5 не наблюдалось. Началось с 3.1.6.
Уже поправил в тестовой версии. 

Получилось вот так
```		
Если ПравоДоступа("Администрирование", Метаданные) И Не РольДоступна("УИ_ПолныеПрава")
			И ПользователиИнформационнойБазы.ПолучитьПользователей().Количество() > 0 Тогда

			ВерсияБСП = УИ_ОбщегоНазначения.ВерсияБСП();
			Если УИ_ОбщегоНазначенияКлиентСервер.СравнитьВерсии(ВерсияБСП, "3.1.6.0") >= 0 Тогда
			//РегистрыСведений.ПараметрыРаботыВерсийРасширений.ЗаполнитьВсеПараметрыРаботыПоследнейВерсииРасширений();
				РезультатПримененияПрав =  УИ_ОбщегоНазначения.РезультатУстановкиПравДоступаДляБСП_3_1_6_ИВыше();
			Иначе
				ТекущийПользователь = ПользователиИнформационнойБазы.ТекущийПользователь();
				ТекущийПользователь.Роли.Добавить(Метаданные.Роли.УИ_ПолныеПрава);
				ТекущийПользователь.Записать();
				
				РезультатПримененияПрав= Истина;
			КонецЕсли;

			ПараметрыСтартаСеанса.Вставить("ДобавленыПраваНаРасширение", РезультатПримененияПрав);
		Иначе
			ПараметрыСтартаСеанса.Вставить("ДобавленыПраваНаРасширение", Ложь);
		КонецЕсли;
```
