### ISSUE TITLE
Не работает автообновление расширения. Притом из конфигуратора все обновляется. 

### ISSUE THREAD

**Issue by unnamsa** [cpr1c/tools_ui_1c#505]
**Опишите ошибку**
При попытке автообновления расширения в режиме предприятия ("Проверка необходимости обновления") возникает ошибка: 
Ошибка применения обновления Ошибка применения расширения Не найден метод "ПриЗавершенииРаботыСистемы", указанный в аннотации метода "УИ_ПриЗавершенииРаботыСистемы".
Толи два толи три последних релиза данное поведение повторяется, в конфигураторе обновление происходит нормально и в дальнейшем ошибка не возникает. Конфигурация типовая с изменениями, в т.ч. через расширения.

**Воспроизведение ошибки**
Конфигурация ERP УХ

**Ожидаемое поведение**
Обновиться 

**Окружение**
Тех информацию скопирую из других инструментов, в УИ не нашел такого пункта:
Платформа: 8.3.23.1688
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP. Управление холдингом (3.1.10.6)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.78.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. di_МодульМСФО (1.3.5.4)
Расширения. EF_00_00491223 ()
Расширения. EF_00_00505696 ()
Расширения. EF_00_00505411_9 ()
Расширения. EF_00_00505899 ()
Расширения. EF_60004956 ()
Расширения. EF_00_00510597 ()
Расширения. EF_10236468_10 ()
Расширения. EF_10236487_9 ()
Расширения. EF_00_00505872 ()
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: http

**Дополнительная информация**

**Comment by unnamsa** [comment]
В настоящее время ошибка возникла при обновлении с 23.6.0 до 23.6.1, точно возникала при попытке обновления до 23.6.0, возможно в предыдущий раз тоже, но подробности прошлой зимы уже сложно вспомнить)

**Comment by unnamsa** [comment]
В конфигураторе проверка применимости:
Проблем применения не обнаружено.
****
Общая проверка с типовыми настройками проверки расширения (включая толстый клиент):
ОбщаяФорма.УИ_РедактированиеТабличногоДокумента.Справка Неразрешимые ссылки на объекты метаданных (2)
ОбщаяФорма.УИ_РедактированиеТабличногоДокумента.Справка Неразрешимые ссылки на картинки (2)
Обработка.УИ_РегистрацияИзмененийДляОбменаДанными.ДополнительнаяФорма Неразрешимые ссылки на объекты метаданных (1)
Обработка.УИ_ПоискИУдалениеДублей.Справка Неразрешимые ссылки на объекты метаданных (3)
{УниверсальныеИнструменты Обработка.УИ_УниверсальныйОбменДаннымиXML.МодульОбъекта(13138,22)}: Переменная не определена (УИ_КоннекторHTTP)
			РезультатВыгрузки=<<?>>УИ_КоннекторHTTP.Post(УИ_АдресПубликацииПриемника + "/hs/tools-ui-1c/exchange", (Проверка: Толстый клиент (управляемое приложение, вариант клиент-сервер))
{УниверсальныеИнструменты Обработка.УИ_УниверсальныйОбменДаннымиXML.МодульОбъекта(13140,24)}: Переменная не определена (УИ_КоннекторHTTP)
			СтруктураРезультата=<<?>>УИ_КоннекторHTTP.КакJson(РезультатВыгрузки); (Проверка: Толстый клиент (управляемое приложение, вариант клиент-сервер))
{УниверсальныеИнструменты Обработка.УИ_УниверсальныйОбменДаннымиXML.Форма.УправляемаяФорма.Форма(804,24)}: Переменная не определена (УИ_КоннекторHTTP)
		РезультатПодключения=<<?>>УИ_КоннекторHTTP.Get(Путь, , ДопПараметры); (Проверка: Тонкий клиент)
{УниверсальныеИнструменты Обработка.УИ_УниверсальныйОбменДаннымиXML.Форма.УправляемаяФорма.Форма(805,24)}: Переменная не определена (УИ_КоннекторHTTP)
		РезультатПодключения=<<?>>УИ_КоннекторHTTP.КакТекст(РезультатПодключения); (Проверка: Тонкий клиент)
{УниверсальныеИнструменты Обработка.УИ_УниверсальныйОбменДаннымиXML.Форма.УправляемаяФорма.Форма(804,24)}: Переменная не определена (УИ_КоннекторHTTP)
		РезультатПодключения=<<?>>УИ_КоннекторHTTP.Get(Путь, , ДопПараметры); (Проверка: Толстый клиент (управляемое приложение, вариант клиент-сервер))
{УниверсальныеИнструменты Обработка.УИ_УниверсальныйОбменДаннымиXML.Форма.УправляемаяФорма.Форма(805,24)}: Переменная не определена (УИ_КоннекторHTTP)
		РезультатПодключения=<<?>>УИ_КоннекторHTTP.КакТекст(РезультатПодключения); (Проверка: Толстый клиент (управляемое приложение, вариант клиент-сервер))

**Comment by unnamsa** [comment]
ПриЗавершенииРаботыСистемы только в расширении УИ находятся

**Comment by LevkinSergey** [comment]
А если через конфигуратор установить обновляется?

**Comment by unnamsa** [comment]
> А если через конфигуратор установить обновляется?

да, и далее работает корректно.

**Comment by LevkinSergey** [comment]
Вот. удивительная история.

**Comment by LevkinSergey** [comment]
Убрал подписку на на событие приложениия "ПриЗавершенииРаботыСистемы", из-за которого не получалось обновить через предприятие.
