### ISSUE TITLE
Ошибка при открытии Универсальных инструментов

### ISSUE THREAD

**Issue by Aaurich** [cpr1c/tools_ui_1c#515]
Добрый день! При открытии внешней обработки "УИ_ПортативныеУниверсальныеИнструменты.epf" сразу же появляется ошибка: "Неизвестное имя формы. Имя: "ВнешняяОбработка.УИ_ПортативныеУниверсальныеИнструменты.Форма"".

 - Версия платформы: 8.3.22.1709;
 - Режим базы данных - серверная;
 - Конфигурация: УНФ 1.6 
 - Версия конфигурации: 1.6.25.236
 - ОС: Windows 10 Pro
 - Версия: 22H2

https://github.com/cpr1c/tools_ui_1c/assets/106876268/61407772-d0d1-4601-9dff-0f49d02d7115

**Comment by LevkinSergey** [comment]
Решилось чисткой серверного кэша
