### ISSUE TITLE
Несколько одинаковых параметров в Консоли запросов

### ISSUE THREAD

**Issue by Oleg1085** [cpr1c/tools_ui_1c#520]
# Описание задачи
1. Добавить возможность использовать насколько параметров в консоли запросов с одинаковым именем.
2. Возможность проставлять флаг какой из параметров использовать
3. Возможность группировать параметры, что бы удобно снимать/ставить флаг использования
![изображение](https://github.com/cpr1c/tools_ui_1c/assets/64373132/b9c8e96a-1ee4-4349-90f9-6f9de4447464)

**Опишите вашу Цель, которую вы сможете достичь с помощью новой функциональности**
При разработке запроса иногда приходится проверять результат запроса с разными значениями параметров. Сейчас приходится создавать копии запросов, и постоянно копировать текст запроса. В итоге путаешься и сбиваешься.
После выше описанной доработкой можно редактировать один текст запроса с разными параметрами по выбору.

**Comment by LevkinSergey** [comment]
п.1 и п.2 реализованы

**Comment by free-archer** [comment]
"п.3 Возможность группировать параметры, что бы удобно снимать/ставить флаг использования"

Это точно нужно, мне кажется только усложнит интерфейс?
