### ISSUE TITLE
Для перечислений показывать имя значения из метаданных

### ISSUE THREAD

**Issue by svsrus81** [cpr1c/tools_ui_1c#542]
# Описание задачи

**Хочется в режиме предприятия точно знать, какое именно перечисление используется с его именем в метаданных**
Сейчас показывается синоним и он, далеко не всегда, даже близко соотносится с именем значения перечисления. Очень не удобно искать потом. А так бы скопировал и вставил в код. 

![2023-10-12 21_58_04](https://github.com/cpr1c/tools_ui_1c/assets/147754121/a7d9b564-90ec-4772-98f9-7a10d3262455)
![2023-10-12 21_59_55](https://github.com/cpr1c/tools_ui_1c/assets/147754121/cdf45ffd-f309-4075-932f-87435250daeb)

**Comment by SkytLees** [comment]
А так бы я назвал все переменные китайской раскладкой, с функциями функцией, с другой раскладкой,  где этот молодой человек, который не имеет желания разбираться в чужом коде, и воспользовался бы к фактическому модулю, через нефактические параметры. ТЗ на то и ТЗ. И если какой-то «умник» такое пишет и утверждает, что ТЗ это старомодно, пускай  идет изучать micropython, хотя бы. С уважением, Никита Арышев.13 окт. 2023 г., в 02:04, svsrus81 ***@***.***> написал(а):﻿
Описание задачи
Хочется в режиме предприятия точно знать, какое именно перечисление используется с его именем в метаданных
Сейчас показывается синоним и он далеко не всегда даже близко соотносится с именем значения перечисления. очень не удобно искать потом. А так бы скопировал и вставил в код.

**Comment by SkytLees** [comment]
Он еще и на гитхабе. Интересно бы посмотреть на его профиль.С уважением, Никита Арышев.14 окт. 2023 г., в 03:47, Nikita Aryshev ***@***.***> написал(а):﻿А так бы я назвал все переменные китайской раскладкой, с функциями функцией, с другой раскладкой,  где этот молодой человек, который не имеет желания разбираться в чужом коде, и воспользовался бы к фактическому модулю, через нефактические параметры. ТЗ на то и ТЗ. И если какой-то «умник» такое пишет и утверждает, что ТЗ это старомодно, пускай  идет изучать micropython, хотя бы. С уважением, Никита Арышев.13 окт. 2023 г., в 02:04, svsrus81 ***@***.***> написал(а):﻿
Описание задачи
Хочется в режиме предприятия точно знать, какое именно перечисление используется с его именем в метаданных
Сейчас показывается синоним и он далеко не всегда даже близко соотносится с именем значения перечисления. очень не удобно искать потом. А так бы скопировал и вставил в код.

**Comment by LevkinSergey** [comment]
@svsrus81 Хорошая идея. Можешь рассказать как интерфейсно ты это видишь?
Пока у меня варианты такие:

- В списке выбора показывать в скобках. 
- Отдельная колонка
- Какое-то сочетание клавиш, при нажатии на которое открывается окошко с информацией о значении.

**Comment by svsrus81** [comment]
@LevkinSergey 
В принципе, идея то не нова, в ИР реализовано. В УИ, по факту, тоже можно глянуть имена значений перечислений через Навигатор по конфигурации, но это отнимает время.

Мое видение такое: для перечислений у вас не задействованы кнопки открытия и выбора значения. Точнее выбор знаечния задействован, но просто показывает выпадающий список. Можно переназначить выбор значения на открытие окна выбора, где будет указан вверху тип "Перечисление.Такоето" и список из двух колонок Представление и Имя. Значения и тип из этого списка можно скопировать.

Ваши варианты тоже имеют место быть, но мне кажется менее удачными. Хотя третий вариант очень похож на то что я предложил, только не нужно сочетания клавиш и показывать все значения.

Могу реализовать сам, без EDT. Код просто передать вам.

**Comment by LevkinSergey** [comment]
Если сами реализуете, будет хорошо. Присылайте тогда расширение с доработками. Объединю сам

**Comment by svsrus81** [comment]
> Если сами реализуете, будет хорошо. Присылайте тогда расширение с доработками. Объединю сам

https://disk.yandex.ru/d/rLUF6XR48qCx6g
