### ISSUE TITLE
Доработать УИ_._От() для поддержки МенеджерВременныхТаблиц

### ISSUE THREAD

**Issue by AlexNecro** [cpr1c/tools_ui_1c#546]
кажется, в некоторых консолях это есть

**Comment by LevkinSergey** [comment]
А что он дальше с этим должен делать? 

Сейчас есть УИ_._ВТ() -  помогает посмотреть в виде структуры состав временных таблиц.

**Comment by LevkinSergey** [comment]
Имею ввиду при отладке запроса открывается в данными этого запроса консоль запроса, при СКД консоль отчетов и т.п.
А что предполагаешь при оталдке менеджера врменных таблиц?

**Comment by AlexNecro** [comment]
В них есть данные, из можно сохранить в тз, а эти тз в консоли поместить
обратно в запрос

**Comment by LevkinSergey** [comment]
Понял. Тогда самое верное будет открывать консоль запросов с пустым запросом и заполненными временными таблицами.

**Comment by AlexNecro** [comment]
Так, стоп, неправильно выразился, я имел ввиду поддержку запроса с
временным таблицами, в ридми вроде написано что так не работает, или я
неправильно понял?

**Comment by LevkinSergey** [comment]
Все работает. Видимо забыл исправить. Можешь прислать место где это указано?
Но идея передавать менеджер временных таблиц в консоль хорошая- реализую

**Comment by LevkinSergey** [comment]
Поправил описание. Спасибо за наводку

**Comment by LevkinSergey** [comment]
В новой версии реализовано
