### ISSUE TITLE
В консоли запросов не подключается редактор Monaco

### ISSUE THREAD

**Issue by lemonza** [cpr1c/tools_ui_1c#560]
**Опишите ошибку**
При открытии консоли запросов, если подключен редактор Monaco, редактор не подключается с сообщением об ошибке:
**Couldn't read a file:// file: file:///C:/Users/.../AppData/Roaming/1C/1cv8/47599434-e521-41f6-8f41-6cdc64a3ce15/93d86427-3453-440e-b40e-36d0a8ee1115/App/tools_ui_1c/24.1.1/Monaco/index.html**

**Воспроизведение ошибки**
1. Открыть **Консоль запросов [УИ]**
2. Увидеть ошибку

**Ожидаемое поведение**
Успешное подключение редактора Monaco

**Окружение**
 - Версия платформы: 8.3.22.2143
 - Режим базы данных: файловая
 - Конфигурация:
 - Версия конфигурации:
 - ОС: Windows 10
 - Версия:
 

**Дополнительная информация**
Предполагаю, что неправильно формируется путь к файлам редактора.
В папке **Monaco** есть подкаталог **src**, которого нет в пути.
Если "вынуть" из него все на уровень вверх, редактор подключается.
![image](https://github.com/cpr1c/tools_ui_1c/assets/32396121/f19fe77a-15e6-4a15-9c05-75b2c8815e65)

**Comment by LevkinSergey** [comment]
Ошибка поправлена в новой версии.
