### ISSUE TITLE
Ошибка загрузки алгоритма по кнопке paste 1C->Загрузить алгоритм

### ISSUE THREAD

**Issue by fishca** [cpr1c/tools_ui_1c#561]
**Опишите ошибку**
При загрузке алгоритма с paste 1C возникает ошибка "Недопустимое значение"

**Воспроизведение ошибки**
1. В консоли запросов выбираем "Paste 1С" -> Загрузить алгоритм
2. Увидеть ошибку
![image](https://github.com/cpr1c/tools_ui_1c/assets/1484649/9b49ec37-f893-4fd7-b0d2-5764e8a508bb)

Подробная информация об ошибке:
![image](https://github.com/cpr1c/tools_ui_1c/assets/1484649/b9e029ee-0e39-4587-bbb4-145ec2de4e14)

Ошибка при установке значения атрибута контекста (Картинка)
{ВнешняяОбработка.УИ_ПортативныеУниверсальныеИнструменты.Форма.УИ_ФормаСсылкиНаКод.Форма(24)}:Элементы.СкопироватьВБуфер.Картинка = УИ_ГЕНЕРАЦИЯ_УИ_БиблиотекаКартинок().УИ_СкопироватьВБуферОбмена;
{ВнешняяОбработка.УИ_РедакторКодаКлиент.Форма.Форма.Форма(1573)}:ОткрытьФорму("ВнешняяОбработка.УИ_ПортативныеУниверсальныеИнструменты.Форма.УИ_ФормаСсылкиНаКод",
{ВнешняяОбработка.УИ_РедакторКодаКлиент.Форма.Форма.Форма(233)}:НачатьЗагрузкуКодаИзСервиса(Новый ОписаниеОповещения("НачатьЗагрузкуКодаИзСервисаЗавершение", ЭтаФорма,
{ВнешняяОбработка.УИ_КонсольЗапросов.Форма.Форма.Форма(1260)}:УИ_ГЕНЕРАЦИЯ_ОбщийМодульПоИмени("УИ_РедакторКодаКлиент", УИ_ГЕНЕРАЦИЯ_КэшОбщихМодулей, ЭтаФорма).ВыполнитьКомандуРедактораКода(ЭтаФорма, Команда);

по причине:
Недопустимое значение

**Ожидаемое поведение**
Ошибки не должно проявляться.

**Окружение**
 - Версия платформы: 8.3.21.1895
 - Режим базы данных - серверная
 - Конфигурация: не имеет значения
 - ОС: Windows Server 2012 R2 Std

 

**Дополнительная информация**
Ошибка проявляется в портативном варианте работы

**Comment by LevkinSergey** [comment]
ошибку поправил.
