### ISSUE TITLE
В редакторе консоли запросов и консоли кода не работает копирование в буфер. Как вариант сделать отдельные кнопки для копирования и вставки в буфер

### ISSUE THREAD

**Issue by GreatZhukov** [cpr1c/tools_ui_1c#562]
Почему то в редакторе консоли запросов и консоли кода не работает Ctrl + C/ Ctrl + V/

Если например копировать из блокнота и вставлять в редактор, то вставка работает в консоли. А вот из консоли если скопировать и вставить в консоль или еще куда-то не получается.  

**Ожидаемое поведение**
Хочется, чтобы можно было копировать из редактора консоли. В консоли запросов каждый раз приходится заходить в конструктор и там копировать текст запроса. В консоли кода вообще никак не скопировать, чтобы в блокнот или в модуль обработки перенести.

**Окружение**
 - Версия платформы: Платформа 8.3.15.1830. Режим совместимости - 8.3.14.
 - Режим базы данных(файловая/серверная/веб):файловая, серверная
 - Конфигурация: БСП 3.1.2.366
 - Версия конфигурации:
 - ОС: Windows Server 2019
 - Версия:
 -

**Comment by LevkinSergey** [comment]
Повторить не получается. Можешь описать алгоритм воспроизведения ошибки?

**Comment by GreatZhukov** [comment]
1. Открываем консоль кода.
2. Пишем любой код.
3. Выделяем код. Нажимаем ctrl + C или Ctrl + X.
4. Открываем блокнот(или любой другой редактор). Нажимаем Ctrl + V.
5. Видим, что скопированный код не вставился.

**Comment by LevkinSergey** [comment]
Попробуй повторить при английской раскладке на клавиатуре. В поле HTML документа по разному срабатывают горячие клавиши на русской и английской раскладке

**Comment by GreatZhukov** [comment]
> Попробуй повторить при английской раскладке на клавиатуре. В поле HTML документа по разному срабатывают горячие клавиши на русской и английской раскладке

Все так же. Пробовал и раскладку менять и в настройках язык синтаксиса на Английский переключить.

Спасает только переключение редактора кода в текст. Тогда копирует.

**Comment by LevkinSergey** [comment]
Попробую повторить окружение. 
Пока мысль только - сделать доп кнопки в редакторе кода для копирования и вставки. Но на них нужно нажимать будет. 
Или поробовать сделать свою обработку для нажатия кнопок ctrl+C ctrl+V на поле редактора. Но тут не уверен, что получится

**Comment by LevkinSergey** [comment]
Ошибку повторил. На новых платформах не проявляется. А вот на 8.3.15.1830 стабильно воспроизводится

**Comment by LevkinSergey** [comment]
В 24.1.3 реализовал настройку для редактора monaco. Которая добавляет в контекстное меню две доп команды для работы с буфером
![image](https://github.com/cpr1c/tools_ui_1c/assets/36307272/48174439-8322-40ff-bf39-d48e71395383)
![image](https://github.com/cpr1c/tools_ui_1c/assets/36307272/3139d784-2f96-4def-9787-ef9c8b1ba856)
