### ISSUE TITLE
В консоли отчетов реализовать сравнение табличного документа (результата)

### ISSUE THREAD

**Issue by free-archer** [cpr1c/tools_ui_1c#564]
В консоли отчетов реализовать сравнение табличного документа (результата) по примеру Инструментов разработчика.

После доработок отчета всегда хочется сравнить старый вариант и новый, чтобы убедится, что ничего не поломалось, не задвоилось.

**Comment by LevkinSergey** [comment]
Сейчас уже есть такой механизм. 
Посмотри насколько он достаточен
![Peek 2024-01-27 19-04](https://github.com/cpr1c/tools_ui_1c/assets/36307272/b9fcc125-4973-45f7-a6bf-e09db077d8ad)

**Comment by free-archer** [comment]
Как то не заметил. Пока устраивает. Спасибо.
