### ISSUE TITLE
Не открывается файл "консоли отчетов" сохраненный в версии 23.6.1 в инструментах версии 24.1.3 

### ISSUE THREAD

**Issue by KoNOnOFFRUS** [cpr1c/tools_ui_1c#569]
**Опишите ошибку**
В "консоли отчетов"  версии 24.1.3,  При открытии файла *.DCR сохранного в консоли Отчетов версии 23.6.1, не отображается информация из файла.

**Воспроизведение ошибки**
1. Запустить обработку "Консоль отчетов"
2. Сделать настройки/Нажать кнопку "открыть файл сохренный в версии 23.6.1"
3. Увидеть ошибку - пустые поля дерева отчетов, вариантов, настроек

**Ожидаемое поведение**
При открытии файлов предыдущих версий "инструментов разработчика"  поддерживается структура сохраненных файлов прошлых версий.

**Окружение**
 - Версия платформы: 8.3.23.2239, 8.3.24.1342
 - Режим базы данных: файловая и серверная
 - Конфигурация: Демонстрационная конфигурация "Библиотека стандартных подсистем", УТ ,ERP
 - Версия конфигурации: SSL 3.1 (3.1.8.334) , УТ11, ERP 2.5.14
 - ОС:  Win10
 - Версия: 22H2
 
[валюты.zip](https://github.com/cpr1c/tools_ui_1c/files/14072589/default.zip)

**Дополнительная информация**

ЗЫ:
Модуль формы;
`Процедура ЗагрузитьФайлКонсолиНаСервер`
вызов:
	ЗначениеВРеквизитФормы(ЗначениеИзФайла(ИмяВременногоФайла), "ДеревоОтчетов");
падает с ошибкой.
т.к. в новых инструментах добавлен реквизит в ДервевоОтчета "ТекстапросаИзСКД"
Как вариант решения:
```
	ДеревоОтчетовИзФайла = ЗначениеИзФайла(ИмяВременногоФайла);
	Если ДеревоОтчетовИзФайла.Колонки.Найти("ТекстапросаИзСКД") = Неопределено Тогда
		ДеревоОтчетовИзФайла.Колонки.Добавить("ТекстапросаИзСКД", Новый ОписаниеТипов("Строка"));
	КонецЕсли;
	ЗначениеВРеквизитФормы(ДеревоОтчетовИзФайла, "ДеревоОтчетов");

```
Далее  вызывается :  `ЗагрузитьСхемуКомпоновкиДанныхВКомпоновщикНастроек()`
проверка :
```
	Если ЭлементДерева.ТипСтроки = 4 Тогда
		Возврат;
	КонецЕсли;

```Падает в "возврат"
в файле "ТипСтроки" = 3

Воспроизведено на "Демонстрационная конфигурация "Библиотека стандартных подсистем", редакция 3.1 (3.1.8.334)"

**Comment by LevkinSergey** [comment]
Поправил обе ошибки в новой версии
