### ISSUE TITLE
Ошибка в обработке "Поиск и удаление дублей"

### ISSUE THREAD

**Issue by dzottula** [cpr1c/tools_ui_1c#57]
Платформа 8.3.13.1690, Бухгалтерия 3.0
При нажатии на кнопку "Поиск дублей" ошибка:

{УниверсальныеИнструменты ОбщийМодуль.УИ_ДлительныеОперацииКлиент.Модуль(104)}: 
Тип не определен (ФормаКлиентскогоПриложения)
			ТипыСвойств.Вставить("ФормаВладелец", Тип("ФормаКлиентскогоПриложения"));

**Comment by LevkinSergey** [comment]
Исправил в develop ветке
