### ISSUE TITLE
Консоль запров Добавлять сумму в документ

### ISSUE THREAD

**Issue by Oleg1085** [cpr1c/tools_ui_1c#572]
Если в консоли запросов выбрали Показывать Итоги переносить эти итоги в табличный документ.
![изображение](https://github.com/cpr1c/tools_ui_1c/assets/64373132/f1c6e6ba-7d74-416d-9280-ef5c89cf08ff)

**Comment by free-archer** [comment]
Реализовал
![image](https://github.com/cpr1c/tools_ui_1c/assets/36464371/c7482dc8-3722-4107-be3e-a81f204a3a86)
