### ISSUE TITLE
Параметры URL 

### ISSUE THREAD

**Issue by LevkinSergey** [cpr1c/tools_ui_1c#589]
Возможность задавать дополнительную таблицу параметров URL, отдельную от самого URL. При вывполнении данные параметры автоматически подкставляются в исполяемый URL
Параметры URL должны автоматически кодироваться в URL для выполнения. Сделать предпросмотр исполняемого URL рядом с параметрами URL

Пример из insomnia

![image](https://github.com/cpr1c/tools_ui_1c/assets/36307272/b71421ed-677a-4a95-a630-78c4a7908a0a)

**Comment by free-archer** [comment]
Я смотрю там уже есть таблица с параметрами URL, только она скрыта и код закомментирован. Это почему так?

**Comment by LevkinSergey** [comment]
> Я смотрю там уже есть таблица с параметрами URL, только она скрыта и код закомментирован. Это почему так?

Не успевал доделать как хотел. К следующему релизу планирую добить
