### ISSUE TITLE
УИ_ВыгрузкаЗагрузкаДанныхXMLСФильтрами

### ISSUE THREAD

**Issue by dunetune** [cpr1c/tools_ui_1c#597]
**Опишите ошибку**
Ошибка при вызове метода контекста (ПрочитатьXML)
{ВнешняяОбработка.УИ_ВыгрузкаЗагрузкаДанныхXMLСФильтрами.МодульОбъекта(282)}:			ЗаписанноеЗначение = Сериализатор.ПрочитатьXML(ЧтениеXML);
{ВнешняяОбработка.УИ_ВыгрузкаЗагрузкаДанныхXMLСФильтрами.Форма.Форма.Форма(585)}:	РеквизитФормыВЗначение("Объект").ВыполнитьЗагрузку(ИмяВременногоФайла);
{ВнешняяОбработка.УИ_ВыгрузкаЗагрузкаДанныхXMLСФильтрами.Форма.Форма.Форма(574)}:	ЗагрузитьДанныеНаСервере(Адрес);
по причине:
Ошибка преобразования данных XDTO:
НачалоСвойства: {http://v8.1c.ru/8.1/data/enterprise/current-config}CatalogObject.Номенклатура	Форма: Элемент	Тип: {http://v8.1c.ru/8.1/data/enterprise/current-config}CatalogObject.Номенклатура
по причине:
Ошибка преобразования данных XDTO:
КонецСвойства: {http://v8.1c.ru/8.1/data/enterprise/current-config}CatalogObject.Номенклатура	Форма: Элемент	Тип: {http://v8.1c.ru/8.1/data/enterprise/current-config}CatalogObject.Номенклатура

по причине:
Ошибка преобразования данных XDTO:
НачалоСвойства: {http://v8.1c.ru/8.1/data/enterprise/current-config}CatalogObject.Номенклатура	Форма: Элемент	Тип: {http://v8.1c.ru/8.1/data/enterprise/current-config}CatalogObject.Номенклатура
по причине:
Ошибка преобразования данных XDTO:
КонецСвойства: {http://v8.1c.ru/8.1/data/enterprise/current-config}CatalogObject.Номенклатура	Форма: Элемент	Тип: {http://v8.1c.ru/8.1/data/enterprise/current-config}CatalogObject.Номенклатура

**Воспроизведение ошибки**
Ошибка возникает при загрузке данных в другую базу. Конфигурация, платформа и релиз идентичные.
Проявилась на  последнем релизе - редакция 3.0 (3.0.148.41) До этого все было хорошо.

**Окружение**
 - Версия платформы: 1С:Предприятие 8.3 (8.3.23.1865).
 - Режим базы данных): Серверный (сжатие: усиленное)
 - Конфигурация: Бухгалтерия предприятия, 
 - Версия конфигурации: редакция 3.0 (3.0.148.41)
 - ОС: Win10
 - Текущая версия инструментов - 24.1.4 (обновил на последнюю, не помогло)
 

**Дополнительная информация**

**Comment by LevkinSergey** [comment]
Обычно такая ошибка возникает, когда в источнике и приемнике различается структура базы данных(имена объектов метаданных и их реквизитов). Может были добавлены/изменены реквизиты в расширениях или доработаны в самой конфигурации?

**Comment by dunetune** [comment]
> Обычно такая ошибка возникает, когда в источнике и приемнике различается структура базы данных(имена объектов метаданных и их реквизитов). Может были добавлены/изменены реквизиты в расширениях или доработаны в самой конфигурации?

Я в курсе. Поэтому и указал, что обе конфы идентичны полностью, типовые, доработок нет. В данном случае причина - новый релиз, в котором что-то и поменялось и обработка документы выгружает, а при загрузке падает в указанную ошибку. На предыдущем релизе обработка выгрузки загрузки работает штатно.

**Comment by LevkinSergey** [comment]
Я бы все равно искал разницу. Метод используется платформенный. Очень давно используется. 
Может выгружал из предыдущего релиза? Или не заметил какого-нибудь расширения. Достаточно одного реквизита

**Comment by dunetune** [comment]
Я понимаю. На предыдущем релизе все работает. Базы обновляются в один день. Все типовые, никаких расширений нет. Сейчас, 29.02 еще новый релиз вышел, попробую на нам после установки проверить. Но сомневаюсь. В релизе 3.0.148.41 сильно что-то доработали. Есть внешние обработки по загрузке доков из сторика в 1С бух, так ее несколько дней правили. Обычно в этот же день делали. Я так понимаю, в этом дело: Сериализатор.ПрочитатьXML(ЧтениеXML) не может прочитать, хотя выгрузка не падает, отрабатывает штатно.

**Comment by dunetune** [comment]
А "чьерт побьери" все таки что-то у меня не так. Я в одну базу пробовал выгружать, а выгружаю обычно из одной(источник) в три разные, по конторам (поэтому и очень подошла с фильтрами). Но в эти дни только по одной базе доки были и не выгружались. Сегодня еще по одной доки прилетели - и все в порядке! Значит буду смотреть, что не так с одной из баз.

**Comment by LevkinSergey** [comment]
Если найдешь косяк в обработке, пришли пожалуйста изменения. Волью в проект

**Comment by dunetune** [comment]
Думаю. что в обработке  все хорошо. В двух базах есть расширения от UCS (для загрузкт доков из сторика .как писал выше).
Вот сегодня буду выгружать, предварительно отключив расширение. И тогда уже точно буду знать.

**Comment by dunetune** [comment]
Да, виновато расширение от UCS. Отключил и все заработало. Спасибо за "пинок" чтобы все проверить еще раз.
