### ISSUE TITLE
Длинна наименования в данных для отладки мала, вы пишете туда дату и время

### ISSUE THREAD

**Issue by LevkinSergey** [cpr1c/tools_ui_1c#61]
Михаил Медведев:
длинна наименования в данных для отладки мала, вы пишете туда дату и время

а она не помещается

**Comment by medm86** [comment]
Управление холдингом 3.0 ( 3.0.10.1)
8.3.16.1063

**Comment by LevkinSergey** [comment]
исправлено в develop ветке
