### ISSUE TITLE
Нужна возможность копировать запрос вместе с параметрами из отладчика в консоль запросов

### ISSUE THREAD

**Issue by sulfur17** [cpr1c/tools_ui_1c#621]
Часто надо выяснить почему запрос выдает не тот результат, который мы ожидаем.
Для этого надо запрос позапускать в консоли.
Но для этого надо и параметры заполнить, а их может быть много и вручную это делать неудобно.

В альтернативных консолях иногда делают возможность получить запрос вместе с параметрами.
Это делается так:
1. в отладчике останавливаемся перед выполнение запроса
2. через Shift+F9 вызываем функцию которая сохраняет контекст запроса куда-то
3. открываем консоль и кнопкой загружаем сохраненный контекст запроса: текст и параметры

**Comment by LevkinSergey** [comment]
Такой механиз реализован. Идет под названием отладка. Позволяет подобным образом анализировать Запрос, СКД с настройками, HTTPзапрос, Ссылки, исполняемую СКД для динамического списка
Вот тут описан механизм https://github.com/cpr1c/tools_ui_1c?tab=readme-ov-file#отладка
