### ISSUE TITLE
Консоль кода (отображение значения переменных)

### ISSUE THREAD

**Issue by MikhailFarbshteyn** [cpr1c/tools_ui_1c#623]
Добрый день. 
В консоли кода хотелось бы видеть значения всех вычисленных переменных. 
Прикладываю картинку для понимания. 
![image](https://github.com/cpr1c/tools_ui_1c/assets/51204853/e70e9657-ee5f-4282-b6e0-a9b76a628dfc)

**Comment by LevkinSergey** [comment]
Первый прототип выглядит вот так. Если есть мысли как это можно интерфейсно улучшить, предлагайте
![Peek 2024-12-06 15-12](https://github.com/user-attachments/assets/389ab04d-825f-417c-9789-094efd1529f8)

**Comment by MikhailFarbshteyn** [comment]
Так уже очень здорово! Спасибо, что сделали, это реально поможет в работе! Не придется постоянно писать Сообщить(Переменная)
