### ISSUE TITLE
Ошибка обработки "Выгрузка и загрузка данных XML" 

### ISSUE THREAD

**Issue by PetrovAnton05** [cpr1c/tools_ui_1c#624]
При использовании обработки "Выгрузка и загрузка данных XML с фильтрами [УИ]" возникает ошибка: 
Поле объекта недоступно для записи (ДатаНачала).

Такая же ошибка возникает с типовой обработкой "ВыгрузкаЗагрузкаДанныхXML", что странно, т.к. эта обработка не используется в расширении. При использовании внешней обработки с сайта ИТС тоже возникает ошибка.
![image](https://github.com/user-attachments/assets/2deef11b-00f0-4f82-805a-031e29b76c33)

![image](https://github.com/user-attachments/assets/957c6c4c-cc94-4d8c-884b-babb11763251)

При отключении расширения - ошибка не возникает. 

Ранее эта ошибка возникала на версии 1.4.13. Но после обновления на v24.1.4 - не исчезла. Расширение типовое, без доработок.

1С:Предприятие 8.3 (8.3.25.1286)
1С:ERP. Управление холдингом (3.2.1.83)

Менял имя формы - не помогло. 
![image](https://github.com/user-attachments/assets/79f810df-9953-4532-8e74-df4a738c4fe7)
![image](https://github.com/user-attachments/assets/1b6816d7-e03e-4580-9931-4138b879e475)

Настройка роли аналогично поставке: 
![image](https://github.com/user-attachments/assets/a5b2f0bc-bb3d-4213-9e9a-fd6360f422fd)

Тип объекта формы как в поставке: 
![image](https://github.com/user-attachments/assets/279383ca-7648-4097-9bd0-39c52dd2ecc3)

**Comment by PetrovAnton05** [comment]
Одинаковые идентификаторы реквизитов 
![image](https://github.com/user-attachments/assets/ce2867eb-e32b-4ebd-a2a0-3017f95571b2)

**Comment by tormozit** [comment]
Это лишь часть картины. А где права для этих реквизитов формы?

**Comment by LevkinSergey** [comment]
Похоже есть какие-то хитрые права на стандартную обработку со специфичными правами для реквизитов обработки.
По идентификатору реквизитов обработки из конфигурации и инструментов были идентичны. Вот он и применял права для обработки из конфигурации к обработке из инструментов. Ну или платформа веселится от того что несколько реквизитов с одним идентифкатором

**Comment by PetrovAnton05** [comment]
Изменили УИДы реквизитов в расширении. В след релизе все должно быть ок)) 
Всем больше спасибо!

**Comment by tormozit** [comment]
Верно ли я понял, что в расширении есть объект метаданных типа "Обработка" с другим именем и идентификатором, но содержащий реквизит с тем же идентификатором, который есть в объекте метаданных конфигурации?

**Comment by PetrovAnton05** [comment]
> Верно ли я понял, что в расширении есть объект метаданных типа "Обработка" с другим именем и идентификатором, но содержащий реквизит с тем же идентификатором, который есть в объекте метаданных конфигурации?

Да.
Типовая обработка "Выгрузка и загрузка данных XML". 
И аналогичная обработка в расширении "Выгрузка и загрузка данных XML с фильтрами [УИ]"
УИДы их реквизитов пересекались.
![image](https://github.com/user-attachments/assets/ca31d3f1-3d03-4b7a-bda8-27a19ffad882)

**Comment by tormozit** [comment]
УИДы обработок точно разные? И в самих объектах нет каких либо других указателей друг на друга?
Если так, то похоже на ошибку платформы и было бы здорово ее отправить в 1С. Я могу помочь с отправкой, Но подготовить отчет тебе нужно самому.

**Comment by PetrovAnton05** [comment]
> УИДы обработок точно разные? И в самих объектах нет каких либо других указателей друг на друга? Если так, то похоже на ошибку платформы и было бы здорово ее отправить в 1С. Я могу помочь с отправкой, Но подготовить отчет тебе нужно самому.

Буду рад, если поможете с отправкой отчета по ошибке в 1С.
УИДы обработок и их форм разные. Имена и синонимы обработок разные. Это отдельные обработки не связанны между собой, кроме УИДов некоторых реквизитов. 
![image](https://github.com/user-attachments/assets/f17231cb-b89e-4ffd-9e4e-d9e5612a9b15)
![image](https://github.com/user-attachments/assets/ceacac36-9ef1-4369-beeb-79b39e918c06)

**Comment by tormozit** [comment]
Образец отчета о проблеме в платформе можно посмотреть тут https://www.hostedredmine.com/issues/989327
