### ISSUE TITLE
Есть ли возможность сделать релиз со всеми .epf в ассетах?

### ISSUE THREAD

**Issue by Bayselonarrend** [cpr1c/tools_ui_1c#625]
Работаю над пакетным менеджером для 1С (ответвление от OpenYellow), который позволил бы быстро подгружать обработки из релизов репозиториев, которые есть в индексе. Расширения там тоже будут, но их можно только скачать, а вот обработки можно прямо на горячую по http получать и сразу подключать из ДД - но для этого они должны быть в ассетах

**Опишите решение**
Сделать релиз, где инструменты будут не в zip, а просто отдельными файлами

**Дополнительная информация**
![1cv8c_Ps2nbdIgk9](https://github.com/user-attachments/assets/5e55ebd4-f456-40d1-b5e1-a0a172491dc4)

**Comment by LevkinSergey** [comment]
Неплохая задумка с менеджером пакетов. 
Отдельными обработками точно нет. Много кода в общих модулях. 
Но сборку в один файл всех инструментов, а не в архив - это возможно. Задача #414.

Как можно пощупать этот пакетный менеджер?

**Comment by Bayselonarrend** [comment]
>Но сборку в один файл всех инструментов, а не в архив - это возможно

Отлично, спасибо. Пока в общем доступе его нет, могу файлом скинуть. Новости будут в [@OpenYellowProject](https://t.me/OpenYellowProject)

[YPM.zip](https://github.com/user-attachments/files/16345831/YPM.zip)

**Comment by LevkinSergey** [comment]
со следующей версии портативная сборка будет в виде одной обработки
