### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by nikon-off** [cpr1c/tools_ui_1c#627]
Как работает кнопка внешней обработки в консоли кода? При нажатии ничего не происходит

**Comment by LevkinSergey** [comment]
Это переключатель режима исполнения кода. Если нажата, то перед выполением алгоритма собирается обработка и она уже запускается, Если нет исполнение идет через оператор Выполнить

Режим выполнения через обработку позволяет в алгоритме писать свои процедуры и вызывать их из кода алгоритма. В том числе выполнять клиент серверный вызов для клиентских алгоритмов

**Comment by LevkinSergey** [comment]
![image](https://github.com/user-attachments/assets/f803be17-0dfe-4657-9bc2-0e9d6653a53f)

![image](https://github.com/user-attachments/assets/c0f14de7-e26b-442e-ae25-f101d0edcbb9)

**Comment by LevkinSergey** [comment]
Ссылки на гифки, там показано как работает

https://private-user-images.githubusercontent.com/36307272/243115801-294ecdc6-2e1d-4bd5-8e99-94b14838756a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjQ4NzAsIm5iZiI6MTcyNjgyNDU3MCwicGF0aCI6Ii8zNjMwNzI3Mi8yNDMxMTU4MDEtMjk0ZWNkYzYtMmUxZC00YmQ1LThlOTktOTRiMTQ4Mzg3NTZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5MjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYThhMjgzYWEyNDg1ZTU2ZWRiYWRkMDk1ZTA5YjJmNzQ1ZWIyZGI5MzRkZWE1NjNlMzljOGY5YWRkNDUwZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RdNVjvMb5liVRHwEfkmrRmNRyzpOyv9e622PzxNRtms

https://private-user-images.githubusercontent.com/36307272/298675452-958733cb-fd7f-4b3f-8c18-edcf92404d23.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjQ4NzAsIm5iZiI6MTcyNjgyNDU3MCwicGF0aCI6Ii8zNjMwNzI3Mi8yOTg2NzU0NTItOTU4NzMzY2ItZmQ3Zi00YjNmLThjMTgtZWRjZjkyNDA0ZDIzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5MjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MWIwOTBmYjRkMWM2MzY1OWNmYjQ3MWEwMDJkYTdjYjAzNjE5YWU4NTljYjlkZDYzOWZjMjU2ZjY4N2MyMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6YTgqdNOOqOSsxtVZETWnGYKlOIS-2fUvCqhAYlkpM0
