### ISSUE TITLE
Непонятная реструктуризация при добавлении расширения

### ISSUE THREAD

**Issue by anton-hystrix** [cpr1c/tools_ui_1c#628]
**Опишите ошибку**
При подключении расширения версии nossl происходит реструктуризация ряда объектов, причём как типовых, так и самописных, вообще никак не связанных ни с типовыми, ни с БСП. Проверить стандартную версию возможности нет, так как в конфигурации очень старая версия БСП без ряда подсистем. Не понимаю, чем вызывается реструктуризация, в конфигурации расширения вижу только новый справочник.

**Воспроизведение ошибки**
1. Подключить расширение nossl через управление расширениями в режиме предприятия.
2. Помимо сообщения о создании справочника алгоритмов выдаются сообщения о реструктуризации ряда объектов. Часть из них типовые, например ИдентификаторыОбъектовМетаданных. Часть пользовательские, справочники, перечисления, регистры сведений.
3. Список объектов всегда одинаковый и воспроизводится при отключении и подключении расширения.

**Ожидаемое поведение**
Реструктуризация объектов не происходит.

**Окружение**
 - Версия платформы: 8.3.26
 - Режим базы данных(файловая/серверная/веб): серверная, MS SQL
 - Конфигурация: Доработанная УТ
 - Версия конфигурации:
 - ОС: Windows
 - Версия: 10

**Дополнительная информация**

**Comment by LevkinSergey** [comment]
Реструктуризация идет, т.к. добавляется новый справочник. И везде где есть любаяСсылка он таблицу реструктуризирует. 

Версия **nossl** -это версия без поддержки интеграции в БСП
Если не нужна реструктуризация лучше брать версии **only_dataprocessors**. Там нет дополнительного справочника
![image](https://github.com/user-attachments/assets/4efc3a88-9093-4e9a-b018-8985c53d08be)

**Comment by anton-hystrix** [comment]
И правда, почему-то совсем забыл про ЛюбаяСсылка. Вы абсолютно правы, спасибо большое за ответ и за ваш проект!
