### ISSUE TITLE
Отсутствует кнопка "Отладить" на форме списка 

### ISSUE THREAD

**Issue by medm86** [cpr1c/tools_ui_1c#63]
в платформе 8.3.16.1063 у меня не появилась кнопка отладить в списке
![image](https://user-images.githubusercontent.com/25048753/73072444-82fc9d80-3ece-11ea-996e-3fd607259de0.png)

**Comment by medm86** [comment]
Управление холдингом 3.0 ( 3.0.10.1)

**Comment by LevkinSergey** [comment]
какой то баг платформы. Пришлось переделать на команду формы с команды объекта. 
Исправлено с develop ветке
