### ISSUE TITLE
Ошибка открытия консоли запросов 8.3.16.1063

### ISSUE THREAD

**Issue by medm86** [cpr1c/tools_ui_1c#64]
![image](https://user-images.githubusercontent.com/25048753/73072511-a4f62000-3ece-11ea-820b-6c042a8a7bd7.png)
не обнаружено использоватьавтозаполнение

**Comment by medm86** [comment]
#12

**Comment by medm86** [comment]
Управление холдингом 3.0 ( 3.0.10.1)

**Comment by LevkinSergey** [comment]
смоделировать не вышло. Управления холдингом нету, пробовал на комплексной. и еще паре конфигураций.

Переделал некоторые реквизиты обработки в реквизиты формы. Поидее может помочь. Будет в релизе 1.4.1. 
Проверьте, пожалуйста, и дайте знать по результатам

**Comment by LevkinSergey** [comment]
Закрываю, т.к. нет информации о повторении ошибки
