### ISSUE TITLE
Сохранение варианта в консоле системы компановки

### ISSUE THREAD

**Issue by Untru** [cpr1c/tools_ui_1c#73]
Проблема следующая, делаю отчет, сохраняю вариант, консоль закрываю, открываю - выскакивает ошибка
http://prntscr.com/qu1gwy Проблема в том что он пытается открыть файл не имея полного имени, то есть условно вместо "С:/Обработки/ИмяФайла.dcr" пытается просто открыть "ИмяФайла.dcr" 
При попытке сохранить вариант который был сохранен до этого выскакивает
http://prntscr.com/qu1i3k
То есть он просто всегда подставляет c:/

**Comment by LevkinSergey** [comment]
исправил в версии 1.4.2
