### ISSUE TITLE
Редактор реквизитов объекта базы данных: ошибка "Недопустимый путь к реквизиту"

### ISSUE THREAD

**Issue by asorozhkin** [cpr1c/tools_ui_1c#74]
В некоторых случаях при выборе редактируемого объекта выдается ошибка "Недопустимый путь к реквизиту" и... список реквизитов не отображается. Иногда помогает установить флаг "Запись без проверок", но не всегда. Закономерность выявить не удалось. Зачастую ругается на стандартные реквизиты типа "Проведен".
Скриншот: https://www.screencast.com/t/wQzahxwJs

1С:Предприятие 8.3 (8.3.12.1685)
Бухгалтерия предприятия, редакция 3.0 (3.0.73.38)
Расширение конфигурации: Универсальные инструменты (1.4.1)

**Comment by LevkinSergey** [comment]
Встроил новый редактор реквизитов. Он побыстрее и пофункциональнее
#82. Выйдет в релизе 1.4.2
