### ISSUE TITLE
Консоль отчетов: ошибка при разворачивании дерева метаданных в конструкторе запроса

### ISSUE THREAD

**Issue by asorozhkin** [cpr1c/tools_ui_1c#75]
В консоли отчётов конструктор СКД запускается только в толстом клиенте, но в нем при разворачивании дерева метаданных в конструкторе запроса возникает ошибка обработчика подписки на событие.
Скриншот: https://www.screencast.com/t/sk0Tq12wQ
Видео-демонстрация: https://www.screencast.com/t/iz5mJ4iN02gC

1С:Предприятие 8.3 (8.3.12.1685)
Бухгалтерия предприятия, редакция 3.0 (3.0.73.38)
Расширение конфигурации: Универсальные инструменты (1.4.1)

**Comment by LevkinSergey** [comment]
К моему сожалению это платформенный косяк. Судя по всему объект **КонструкторСхемыКомпоновкиДанных** работает как толстый клиент обычное приложение. 
мать ее.....

Написал запрос в 1С. Посмотрим что ответят

**Comment by asorozhkin** [comment]
Подобная ошибка обработчика подписки на событие возникает и в консоли запросов при работе в толстом клиенте. 

Поэтому предполагаю, что причина в следующем: процедуры обработки подписки на событие в тонком клиенте выполняются на сервере (поэтому видят серверный общий модуль), а в толстом клиенте выполняются на клиенте (поэтому не видят серверный общий модуль).

Ранее в подобной ситуации помогло установить у серверного общего модуля признак "Вызов сервера" в свойствах.

**Comment by LevkinSergey** [comment]
Ваш вариант более правильный получается. 
Могу предложить такой выход. Сделать возможность редактировать текст запросов наборов записей, не проваливаясь в КонструкторСхемаКомпоновкиДанных, с использованием консоли запросов непосредственно из формы консоли или отдельной формы.

Таким образом запросы сможем редактировать в тонком клиенте, а всю остальную настройку делать не трогая запросы в толстом. Не очень удобно, но проблему обойти поможет.

Идеальным вариантом было бы сделать аналог конструктора СКД на тонком клиенте, но эта задача сама по себе весьма трудоемка, плюс к этому всегда существуюет вероятность, что 1С выпустит его в следующем релизе. Поэтому если и делать, то в сильно упрощенном варианте

Что скажете?

**Comment by LevkinSergey** [comment]
Завел соответствующую задачу #84

**Comment by asorozhkin** [comment]
Если бы в толстом клиенте Консоль отчетов работала бы без ошибок (подписки на события), я пользовался бы ею.
В тонком клиенте пробовал загружать из xml (выгруженных в Конфигураторе) саму схему и настройки вывода. Работает. Но функционал с уровня Предприятия ограничивается настройкой вариантов отчета. Аналогичные действия можно сделать во внешнем отчете. Поэтому, на мой взгляд, не имеет смысла тратить силы и время на разработку упрощенной версии Конструктора СКД для тонкого клиента.

**Comment by Terverus** [comment]
Кстати, конструктор схемы СКД запускается только из толстого клиента и только когда консоль СКД встроена в конфигурацию. ПРи запуске из расширения все равно ругается, что надо запускать в толстом клиенте, хотя уже консоль запущена в толстом клиенте.

**Comment by asorozhkin** [comment]
Я не встраивал в конфигурацию (подключал расширение). В толстом клиенте конструктор открывался, но не давал перетащить метаданные в запрос.

**Comment by LevkinSergey** [comment]
@Terverus Можешь скрин сделать или видос с оишбкой? Какая платформа, конфа, Версия УИ?

**Comment by LevkinSergey** [comment]
Реализован инструмент для редактирования скд в тонком клиенте. Проблемы с недобавлением для толстого клиента метаданных должны уйти
