### ISSUE TITLE
Алгоритмы: ошибка при добавлении параметра

### ISSUE THREAD

**Issue by asorozhkin** [cpr1c/tools_ui_1c#76]
Добавил в справочник "УИ_Алгоритмы" новый элемент. Записал. На вкладке "Параметры" нажал кнопку "(+) Добавить параметр". Получил ошибку "Переменная не определена"
https://www.screencast.com/t/ByLwLNeEcH

1С:Предприятие 8.3 (8.3.12.1685)
Бухгалтерия предприятия, редакция 3.0 (3.0.73.38)
Расширение конфигурации: Универсальные инструменты (1.4.1)

**Comment by LevkinSergey** [comment]
Пока этот модуль не до конца интегрирован. Потому и не описал его. Включил в релиз следующей недели

**Comment by LkMaksimka** [comment]
Универсальные инструменты (1.4.14) - ошибка не воспроизвелась
![Алгоритмы_ошибка при добавлении параметра_76](https://user-images.githubusercontent.com/23025375/201409810-a93178a9-4248-4b6b-bc6c-9a652e22dd25.gif)
