### ISSUE TITLE
Групповая обработка справочников и документов: нет возможности открыть объект

### ISSUE THREAD

**Issue by asorozhkin** [cpr1c/tools_ui_1c#77]
На вкладке "Найденные объекты" недоступно открытие объекта из отобранного списка (например, двойным щелчком ЛКМ)

1С:Предприятие 8.3 (8.3.12.1685)
Бухгалтерия предприятия, редакция 3.0 (3.0.73.38)
Расширение конфигурации: Универсальные инструменты (1.4.1)

**Comment by LevkinSergey** [comment]
Исправил в релизе 1.4.2
