### ISSUE TITLE
Исправить алгоритмы обработки "Редактор реквизитов объекта базы данных"

### ISSUE THREAD

**Issue by vlaboris1c** [cpr1c/tools_ui_1c#81]
Исправьте, пожалуйста, алгоритмы обработки.
Сейчас перезаписываются абсолютно все реквизиты.
Наверное, надо сделать так, **_чтобы записывались только измененные_**?

В форме обработки я выбрал элемент справочника "Банки" и изменил только реквизит "Телефоны", а обработка пошла изменять все:

Поле объекта недоступно для записи (ЭтоГруппа)
{УниверсальныеИнструменты Обработка.УИ_РедакторРеквизитовОбъекта.Форма.Форма.Форма(1010)}:		ОбъектЗаписи[ТекРеквизит.Имя] = ЭтотОбъект[ТекРеквизит.ИмяРеквизитаФормы];
{УниверсальныеИнструменты Обработка.УИ_РедакторРеквизитовОбъекта.Форма.Форма.Форма(1069)}:	ЗаполнитьРеквизитыНаСервереПередЗаписью(ОбъектЗаписи);
{УниверсальныеИнструменты Обработка.УИ_РедакторРеквизитовОбъекта.Форма.Форма.Форма(97)}:	ЗаписатьНаСервере();

**Comment by LevkinSergey** [comment]
Сделал запись только измененных объектов. Это будет в релизе 1.4.2.

**Comment by LevkinSergey** [comment]
Встроил новый редактор реквизитов. Он побыстрее и пофункциональнее
 #82. Выйдет в релизе 1.4.2
